### ISSUE TITLE
Controller: subscription vs no-subscription

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#416]
We defined a few differences in controller behavior based on the the presence of a subscription.

Let's identify 2 different scenarios:

- Controller and firewall both community (without subscription)

- Controller and firewall enterprise (both with subscription)

Controller community (without subscription)

- The community controller allows registration of up to 3 units.

- Only community firewalls can register with the community controller.

Controller enterprise (with subscription)

- The enterprise controller is not limited in the number of units (or has higher limits).

- The enterprise controller accepts registration ONLY from enterprise firewalls.

This way, we're clearly delineating the two domains.

**Comment by andre8244** [comment]
Released in:
- ns8-nethsecurity-controller 0.0.17
- ns-ui 0.65.0
