### ISSUE TITLE
FlashStart: DNS resolution fails after disabling service

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#422]
**Steps to reproduce**

* Enable FlashStart by following steps on #420 
* Disable FlashStart.

**Expected behavior**

Clients must be able to normally execute DNS queries.

**Actual behavior**

Clients are trying to connect to dnsmasq but dnsmasq points to dnsdist which is not currently running.

**Components**

Same of #420

**Comment by gsanchietti** [comment]
It seems that some address may still be in cache: a full restart is required for dnsmasq.

**Comment by cotosso** [comment]
I have some difficulty to reproduce again the problem.
However, I don't mind having a restart when we press "save" button, since it's a very rare occurrence.

**Comment by gsanchietti** [comment]
Ok, let's keep the restart so we make sure the dnmasq configuration is re-generated.
