### ISSUE TITLE
OpenVPN RW: hosts unreachable with bridged configuration 

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#445]
**Steps to reproduce**

- Configure a VPN Roadwarrior server in bridged mode.
- Select an existing bridge (e.g., br-lan) to connect the VPN to.
- Start the VPN.
- Unable to reach any hosts on the local network.
- Check the bridge with the `brctl show` command. The taprw interface does not appear in the list of interfaces for the bridge.

**Expected behavior**

The taprw interface should be correctly added to the selected bridge during the configuration of the bridged VPN Roadwarrior, allowing for a functional VPN connection that can reach hosts on the local network.

**Actual behavior**

The taprw interface is not correctly added to the selected bridge during the VPN Roadwarrior configuration. This results in the VPN connection not working properly, making it impossible to reach hosts on the local network.

**Components**

Version: 8-23.05.3-ns.0.0.3-rc1
Packages:
- ns-api - 0.0.64-1
- ns-openvpn - 0.0.2-1

**Workaround**

Manually edit the bridge from the 'interfaces and devices' section and add the taprw interface. After this modification, it is possible to correctly reach hosts on the LAN through the VPN.

**Comment by cotosso** [comment]
Now taprw1 device is automatically added to the bridge and it works flawlessy.

OpenVPN RW server deletion still needs some fix, after having deleted the RW server:

* From the UI I can see taprw1 removed from the bridge (this is ok)

![image](https://github.com/NethServer/nethsecurity/assets/7226896/6077fe9f-b734-47da-abe0-6c69f370e733)


* But the device taprw1 is still present among unused devices (should be not present anymore)

![image](https://github.com/NethServer/nethsecurity/assets/7226896/ce4d650f-7363-459b-9c32-1c918a829314)

* taprw1 is still inside the bridge:

![image](https://github.com/NethServer/nethsecurity/assets/7226896/3935558b-2944-42fd-b369-92b6ccdef7ae)

**Comment by gsanchietti** [comment]
Leaving the tap device in place doesn't cause issues, even with additional bridged servers. However, removing the device before OpenVPN restarts leads to OpenVPN freezing and consuming CPU. Restarting OpenVPN or making a network change resolves the issue.

Since this is a cosmetic issue, we are going to keep the current behavior.
