### ISSUE TITLE
Port forward: change reflection option label

### ISSUE THREAD

**Issue by andre8244** [NethServer/nethsecurity#457]
If destination zone is unselected web ui shows the option “Any zone” .

![Image](https://github.com/NethServer/nethsecurity/assets/804596/75d30550-a66f-4912-b76d-ae0448a080d6)

Actually whats is done by the system is to find the right destination zone (based on the ip address)  and using it.

I propose to substitute “Any zone” with “Auto” to better explain what is happening.

**Comment by gsanchietti** [comment]
Verified.
