### ISSUE TITLE
DHCP: scan network

### ISSUE THREAD

**Issue by andre8244** [NethServer/nethsecurity#460]
Expose the same feature present on NS7:

the user should be able to execute an arp scan to a given network device

the UI should list all devices found; if a device does not have a reservation, display also a button to create the reservation

[Mockups](https://www.figma.com/file/FhVUA3F59rOsQPh2bDlZ7V/Nethsecurity-shared-file?type=design&node-id=1%3A2&mode=design&t=GEcahlgbTxpwaWxy-1) (Network section, marked as Ready in blue)

NS7 screenshot:

![Image](https://github.com/NethServer/nethsecurity/assets/804596/dd52bc26-1331-4c59-9e82-5d248bac1859)

**Comment by gsanchietti** [comment]
Verified.
