### ISSUE TITLE
IPsec: remote/local network validator

### ISSUE THREAD

**Issue by andre8244** [NethServer/nethsecurity#465]
Prevent users to enter the same network on both local an remote fields.

Private discussion: https://mattermost.nethesis.it/nethesis/pl/yc9bwcgdctyiunaabpkxw8puua

**Comment by gsanchietti** [comment]
Testing image: 23.05.3-ns.0.0.3-rc1-79-g3de4963

**Comment by gsanchietti** [comment]
Verified.
