### ISSUE TITLE
OpenVPN RW: LDAP database only for subscription

### ISSUE THREAD

**Issue by andre8244** [NethServer/nethsecurity#470]
The LDAP database will be a feature available only with a subscription.

If the machine is not registered, the button will be grayed out and a tooltip will explain that you need a subscription to use it.

Also change button label to "Add remote database".

**Comment by andre8244** [comment]
Testing image version: 23.05.3-ns.0.0.5-rc2-3-g20f2cdd

**Comment by gsanchietti** [comment]
Verified: the button to enable the LDAP database is present with a community or enterprise subscription.
