### ISSUE TITLE
IPsec: better expose PFS option

### ISSUE THREAD

**Issue by andre8244** [NethServer/nethsecurity#477]
Feedback from users course regarding PFS in IPSEC.

Currently we managed it this way with default 2048 bit (DH-14)

This way the PFS option (that is usually in a separate box) is a little hidden and very likely will lead to many support requests.

![Image](https://github.com/NethServer/nethsecurity/assets/804596/18c6e89b-3be7-40ca-9344-b67c8ff9a77a)

Changes:
- move the PFS label near DH group

**Comment by andre8244** [comment]
Testing image version: 23.05.3-ns.0.0.5-rc2-6-gda79335

**Comment by gsanchietti** [comment]
Verified.
