### ISSUE TITLE
Dashboard: notification of new available version

### ISSUE THREAD

**Issue by andre8244** [NethServer/nethsecurity#478]
Display a notification if newer image is available.

![Image](https://github.com/NethServer/nethsecurity/assets/804596/aa7d492b-6632-4bb3-b118-99eff0981634)

**Comment by andre8244** [comment]
Testing image version: 23.05.3-ns.0.0.5-rc2-3-g20f2cdd

**Comment by gsanchietti** [comment]
Verified: if the version is not the latest, an "Update" label appears
