### ISSUE TITLE
firewall rules: change cyan color when disabled

### ISSUE THREAD

**Issue by andre8244** [NethServer/nethsecurity#480]
When a firewall rule is disabled, everything should be disabled except for the Edit button and the Kebab menu.

Edit: we decided to keep cyan buttons and to use a semitransparent background instead

![Image](https://github.com/NethServer/nethsecurity/assets/804596/d33431e4-3ef4-48e8-b3be-2f1cb3188492)

**Comment by andre8244** [comment]
Testing image version: 23.05.3-ns.0.0.5-rc2-3-g20f2cdd

**Comment by gsanchietti** [comment]
Verified: the zone is now grayed-out when the rule is disabled.
