### ISSUE TITLE
Zones and policies: improving drawer for WAN zone

### ISSUE THREAD

**Issue by andre8244** [NethServer/nethsecurity#488]
Drawer may not be consistent if used for WAN zone:

![Image](https://github.com/NethServer/nethsecurity/assets/7226896/c5c1a6b2-5907-41ef-87b3-7656bdacb94d)

Traffic to WAN selector is meaningless in this specific case.

Link to internal discussion:
https://mattermost.nethesis.it/nethesis/pl/fktqmnwijjr63miiork8efh1ow

**Comment by andre8244** [comment]
Testing image version: 23.05.3-ns.0.0.5-rc2-6-gda79335

**Comment by gsanchietti** [comment]
Verified: the toggle is not present when editing the WAN zone
