### ISSUE TITLE
Controller: can't connect unit if UI is disabled on port 443

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#490]
**Steps to reproduce**

- Disable the web interface on port 443 following the [documentation](https://docs.nethsecurity.org/en/latest/remote_access.html#disable-web-user-interface-on-port-443).
- Attempt to connect a new unit to the controller.

**Expected behavior**

The controller should connect the new unit correctly, displaying the unit name and allowing it to be opened without issues.

**Actual behavior**

After disabling the web interface as explained in the documentation, the controller shows the new unit as connected but fails to display the unit name. Additionally, when attempting to "Open unit," the operation fails.

**Components**

NethSecurity version: 8-23.05.3-ns.0.0.3-rc1-80-g615c01e

**See also**

https://community.nethserver.org/t/nethsecurity-controller-doesnt-work-when-the-nethsec-web-interface-is-disabled/23517

----

Thanks to **mrarkuz** for reporting

**Comment by gsanchietti** [comment]
Check the bug is not reproducible.

Use `latest` tag for the ns8-nethsecurity-controller module: https://github.com/NethServer/ns8-nethsecurity-controller?tab=readme-ov-file#install

**Comment by andre8244** [comment]
After disabling the web interface on port 443, units can be connected and opened successfully

**Comment by gsanchietti** [comment]
Fix released on ghcr.io/nethserver/nethsecurity-controller:0.0.18
