### ISSUE TITLE
Subscription: can't register a community subscription

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#491]
**Steps to reproduce**

- Access my.nethserver.com and create a new trial
- Access the subscription page.
- Paste the token generated by my.nethserver.com to activate the subscription on the firewall.

**Expected behavior**

The machine should be registered correctly using the token generated by my.nethserver.com.

**Actual behavior**

After pasting the token to activate the subscription on the firewall, the machine is not registered correctly. The server returns the error: `{"error": "invalid_secret_or_server_not_found"}`.

**Components**

NethSecurity version: 8-23.05.3-ns.0.0.3-rc1-80-g615c01e

**See also**

https://community.nethserver.org/t/openvpn-ubus-request-failed/23509

----

Thanks to **MadPatrick** for reporing

**Comment by andre8244** [comment]
QA: the machine is successfully registered, but the displayed expiration date is wrong, e.g. "1/20/1970"

**Comment by andre8244** [comment]
@MadPatrick we just fixed the expiration date, we are building a new release including the fix.

About the update/downgrade, that's expected: subscription users have access to stable versions only, and RC2 is currently the latest "stable" release. Moreover, only stable versions are officially supported (if included in your subscription plan).

**Comment by MadPatrick** [comment]
Ok. That makes sense.
Then i'll stay unregistered for the moment ;-)

**Comment by andre8244** [comment]
Subscription expiration date has been fixed in [23.05.3-ns.0.0.5-rc2-26-gb3db7a3](https://updates.nethsecurity.nethserver.org/dev/8-23.05.3-ns.0.0.5-rc2-26-gb3db7a3/targets/x86/64/nethsecurity-8-23.05.3-ns.0.0.5-rc2-26-gb3db7a3-x86-64-generic-squashfs-combined-efi.img.gz)

**Comment by andre8244** [comment]
Verified
