### ISSUE TITLE
Threat shield: empty subscription feed

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/nethsecurity#496]
The 5 feeds for subscribed systems are always empty.

**Steps to reproduce**

- Subscribe the system
- Enable the nethesis level 3 feed

**Expected behavior**

`nft list set inet banIP nethesislvl3v4` shows a list of IPs.

**Actual behavior**

```
May 3 17:09:47 fw banIP-0.9.4-3[16535]: skip empty feed 'nethesislvl3v4'
```

**Components**

ns-threat_shield - 0.0.2-1

**Comment by gsanchietti** [comment]
The change has been introduced by this commit banip commit: https://github.com/openwrt/packages/commit/5af101564a9f889807e0e2762934e03cb0259eb1

**Comment by gsanchietti** [comment]
Testing image: 23.05.3-ns.0.0.5-rc2-26-gb3db7a3

**Comment by gsanchietti** [comment]
Verified: after applying the patch, the sets are correctly loaded.

But I've found another bug, see #507
