### ISSUE TITLE
ns-api: auto updates not applied

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/nethsecurity#497]
Daily updates are not applied due to a cron syntax error.

**Steps to reproduce**

- Enable Automatic updates for Bug & security fixes
- Look at /var/log/messages for errors:
```
May  3 12:28:16 fw crond[3387]: crond (busybox 1.36.1) started, log level 5
May  3 12:28:16 fw crond[3387]: user root: parse error at sleep
```

**Components**

ns-api-0.0.67-1

**Comment by gsanchietti** [comment]
Testing image: 23.05.3-ns.0.0.5-rc2-26-gb3db7a3

**Comment by gsanchietti** [comment]
Verified: cron does not report an error anymore
