### ISSUE TITLE
Auto logoff after closing browser tab

### ISSUE THREAD

**Issue by MadPatrick** [NethServer/nethsecurity#498]
I noticed that the webmenu stays accesable after closing the browser or restarting the computer
This gives error because the connection was lost, but don't disappear itself

can there be a time out to log off automatically

**Comment by gsanchietti** [comment]
This is not a bug, this is the intended behavior. Maybe we can refine the UI a bit.
Please try to clarify your point inside a community discussion.
You can also use the existing one: https://community.nethserver.org/t/nethsecurity-and-login-session/23336
