### ISSUE TITLE
Charts in dashboard Top weekly and monthly

### ISSUE THREAD

**Issue by MadPatrick** [NethServer/nethsecurity#499]
Hi,

I like the traffic charts in the dashboard, but is it possible to show this also for weekly/monthly instead of only daily

**Comment by gsanchietti** [comment]
The dashboard just shows the available data, assuming that only daily data are available.
Stats are volatile: they are lost upon firewall reboot. We plan to extend such king of reports in the future.

Please, for new feature requests [open a new discussion inside the community](Stats are volatile: they are lost upon firewall reboot.).
