### ISSUE TITLE
Network page: show VPN interfaces

### ISSUE THREAD

**Issue by andre8244** [NethServer/nethsecurity#506]
Show VPN interfaces as in the UI mockup

![vpn ifaces](https://github.com/NethServer/nethsecurity/assets/4612169/bc884b2e-2cfa-41b9-b5b9-602ce353bb99)

Required changes:
- remove connection and enabled/disabled status
- decide what networks should be visible

Visible networks should be these ones:

-  IPsec and OpenVPN tunnels: all remote networks declared in the tunnel so that we know wich network is carried by which interface (they should be usually 1 network, sometimes 2 networks, rarely 3 or more networks)

If there are multiple networks, show them one below the other e.g.
10.10.10.0/24
10.20.20.0/24
10.55.55.0/24

- OpenVPN RW : network used by OpenVPN RW server (all clients will have an ip from this network)

**Comment by andre8244** [comment]
Testing image version: [23.05.3-ns.0.0.5-rc2-45-g5a9e354](https://updates.nethsecurity.nethserver.org/dev/8-23.05.3-ns.0.0.5-rc2-45-g5a9e354/targets/x86/64/nethsecurity-8-23.05.3-ns.0.0.5-rc2-45-g5a9e354-x86-64-generic-squashfs-combined-efi.img.gz)

**Comment by cotosso** [comment]
I tested it, now they are as supposed, except for the ipsec tunnels that has a behaviour different from other VPNs, it displays no tunnel name, only device name (in the same position as other ones have vpn name).
See image 
![image](https://github.com/NethServer/nethsecurity/assets/7226896/be3bb028-8d25-43b0-a479-b95b466adc02)

**Comment by andre8244** [comment]
Testing image: 23.05.3-ns.0.0.5-rc2-61-gc741694

**Comment by cotosso** [comment]
now ipsec tunnel is correctly displayed :
![image](https://github.com/NethServer/nethsecurity/assets/7226896/3176ce29-30b9-4245-bfbb-c0e4d1137472)
