### ISSUE TITLE
Threat shield not started from the UI

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#507]
**Description**

Threat shield fails to start when enabled from the user interface.

**Steps to reproduce**

1. Access the Threat Shield page.
2. Go to the Settings tab and enable the service.
3. Enable at least one blocklist.
4. Apply the changes.

**Expected behavior**

Threat Shield should start after enabling the service, and the BanIP service should be active.

**Actual behavior**

Despite enabling Threat Shield and applying changes, the BanIP service remains inactive.

Since the service is somehow disabled, ubus signal to reload the lists is ignored.

Evidence:

```
# /etc/init.d/banip status
::: banIP runtime information
  + status            : disabled (nft: ✘, monitor: ✘)
  + version           : -
  + element_count     : 0
  ...
  + last_run          : -
  + system_info       : cores: , memory: , device: 
```

The service is enabled but inactive:

```
# /etc/init.d/banip enabled && echo "enabled!"
enabled!
```

**Components**

NethSecurity version: 8-23.05.3-ns.0.0.5-rc2-28-g4568df6

**Workaround**

Execute:
```
/etc/init.d/banip restart
```

**Comment by cotosso** [comment]
Threat shield (banip)  now starts and stops as expected from the web UI.
Approved
