### ISSUE TITLE
Migration: threat shield IP not migrated

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#522]
When migrating from NethServer 7, the configuration of Threat Shield IP is not migrated.

**Steps to reproduce**

1. Perform a migration from NethServer 7 to NethSecurity 8.
2. Observe the configuration of Threat Shield IP after migration.

**Expected behavior**

The configuration, including Nethesis/Yoroy premium lists, should be migrated and restored on NethSecurity 8 if they were enabled on NethServer 7.

**Actual behavior**

The migration process does not transfer any configuration related to Threat Shield IP from NethServer 7 to NethSecurity 8.

**Components**

NethSecurity version: 8-23.05.3-ns.0.0.5-rc2-52-gc0e771f

**Comment by cotosso** [comment]
tested the migration with exported file and different hardware:
the migrated json seems to be ok:
`{"ts-dns":{"adb_bypass":[],"adb_forcedns":"0","ts_enabled":"0","adb_enabled":"0","adb_sources":[]},"ts-ip":{"status":"1","allow":[],"categories":["yoroimallvl1","yoroimallvl2","yoroisusplvl2"]}}`

I have errors on threat shield page (blocklists, allowlist and settings)
![image](https://github.com/NethServer/nethsecurity/assets/7226896/83699573-aed2-4e13-9d90-43020699ccaf)

command output

```
root@vmtest:~# /usr/libexec/rpcd/ns.threatshield call list-settings
  File "/usr/libexec/rpcd/ns.threatshield", line 156
    pass:
    ^^^^
SyntaxError: expected 'except' or 'finally' block

root@vmtest:~# /usr/libexec/rpcd/ns.threatshield call list-blocklist
  File "/usr/libexec/rpcd/ns.threatshield", line 156
    pass:
    ^^^^
SyntaxError: expected 'except' or 'finally' block
```

**Comment by gsanchietti** [comment]
The reported error is not related to this issue but a regression of #546.

I'm setting this to verified.
