### ISSUE TITLE
EFI: can't use free space as extra storage

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#529]
On a machine using EFI, it is not possible to utilize additional storage.

**Steps to reproduce**

1. Install NethSecurity on a disk larger than 300MB.
2. Ensure that the machine boots using EFI.
3. Access the "Storage" page.

**Expected behavior**

It should be possible to partition the existing disk to utilize the space for data storage.

**Actual behavior**

The free space is not usable.

Related to #492 

**Components**

NethSecurity version: 23.05.3-ns.0.0.5-rc2-61-gc741694

**Comment by gsanchietti** [comment]
**Test case 1**

Check the issue is not reproducible on a EFI machine

**Test case 2**

Check the issue is not reproducible on a legacy-BIOS machine

**Comment by cotosso** [comment]
Tested and working as expected.

case 1 : EFI
![image](https://github.com/NethServer/nethsecurity/assets/7226896/38f5e80b-a124-4d06-a72d-0a89e6099588)

case 2: legacy BIOS
![image](https://github.com/NethServer/nethsecurity/assets/7226896/3180f6b6-63ff-4898-b7b1-3e85ebd9f7d7)

thanks to @francio87
