### ISSUE TITLE
Zone: force creation in lowercase

### ISSUE THREAD

**Issue by andre8244** [NethServer/nethsecurity#533]
The zone page shows special icons if the zone has a specific name, like 'guests'.
If the zone is named in uppercase, like `GUESTS` the icon is not displayed.
All the zones are displayed always in uppercase inside the UI.

Suggested change:
- the UI must force the zone name in lowercase when saving it to the db
- the UI must always display the zones in uppercase (this should be already true)

Private discussion: https://mattermost.nethesis.it/nethesis/pl/5nmu49u5jf8f8g97nzymgky3br

**Comment by andre8244** [comment]
Testing image: 23.05.3-ns.0.0.5-rc2-73-g6b92586

**Comment by francio87** [comment]
confirm, fixed.
