### ISSUE TITLE
Inventory: basic usage statistics

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#537]
Gather anonymous statistics on system usage.

Analyze data to identify:
- Most and least used features.
- Usage trends and patterns.
- Areas for improvement and potential new features.

Data to collect:
- [x] hotspot: enabled yes/no
- [x] flashstart: enabled yes/no
- [x] openvpnrw: number of servers
- [x] openvpn tun: number of servers
- [x] openvpn tun: number of clients
- [x] subscription status: no, enteprise, community
- [x] connected to a controller: yes/no
- [x] threat shield: enabled yes/no
- [x] extra storage: no, yes, partition
- [x] threat shield: number of enterprise list
- [x] number of proxy pass
- [x] number of dpi rules
- [x] threat shield: number of community lists
- [x] luci enabled: yes/no
- [x] network: number of interfaces
- [x] dhcp: enabled yes/no
- [x] multiwan: type of default policy balance/backup/custom
- [x] qos: number of interfaces
- [x] ipsec: number of tunnels
- [x] network: number of ipv6 interfaces

**Comment by Tbaile** [comment]
On a fresh installation the phonehome script fails:
```
File "/usr/lib/python3.11/site-packages/nethsec/inventory/__init__.py", line 59, in fact_threat_shield
```

This is because the `ban_feed` field doesn't exists

Also, `mwan.type` is `null` when no multi wan is configured, I'd remove the field entirely

**Comment by gsanchietti** [comment]
I prefer to keep the mwan field even if empty, it's still a valid information.

I'm going to fix the banip fact.

**Comment by gsanchietti** [comment]
Testing image version: [8-23.05.3-ns.0.0.5-rc2-80-g3318916](https://updates.nethsecurity.nethserver.org/dev/8-23.05.3-ns.0.0.5-rc2-80-g3318916/targets/x86/64/nethsecurity-8-23.05.3-ns.0.0.5-rc2-80-g3318916-x86-64-generic-squashfs-combined-efi.img.gz)

**Comment by Tbaile** [comment]
> mwan field

Not the whole mwan field, just the `type` one, but fine either way
