### ISSUE TITLE
Active ftp sessions do not transfer files

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/nethsecurity#544]
NethSecurity is missing the helper to allow active FTP sessions.

**Steps to reproduce**

- Connect to an FTP server in active mode (windows ftp.exe is perfect, it only supports active mode)
- List remote files or try to transfer a file

**Expected behavior**

List or file

**Actual behavior**

Timeout
```
ftp> ls
421 Service not available, remote server has closed connection
```

---

Thanks to Angelo

**Comment by gsanchietti** [comment]
Test image: 23.05.3-ns.0.0.5-rc2-93-gd42e52c

**Test case 1**

On a new machine, verify that FTP active transfer can be achieved after following this doc: https://dev.nethsecurity.org/design/nat_helpers/

**Test case 2**

On a migrated machine,  verify that FTP active transfer can be achieved without changing the configuration.
