### ISSUE TITLE
API server does not always starts at boot

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#563]
**Description**

Sometimes, the `nethsecurity-api` service does not start at boot. The issue is not consistently reproducible, and logs do not provide clues because `procd` captures all output without logging anything in `/var/log/messages`.

**Tests Conducted**

- Mounted temporary filesystem
- Checked presence of loopback network interface
- Set environment variables
- Changed log destination
- Used a traditional init.d script

**Findings**

The only effective solution was to delay the startup. Adding a one-second sleep on a reproducible machine resolved the issue.

**Proposed Solution**

- Move the startup later, from priority 90 to 99.
- Add a variable to allow further delay if necessary.

**Workaround**

Manually restart the service:
```
/etc/init.d/ns-api-server restart
```

**Components**

NethSecurity version: 8-23.05.3-ns.1.0.0

**Comment by mamengoni** [comment]
Tested and verified!
