### ISSUE TITLE
Firewall objects

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#567]
**Why is this feature being requested?**
1. The need for enhanced firewall management through organized and structured IP and domain sets.
2. To simplify and automate the handling of firewall rules, port forwards, multiwan rules, and DPI rules by using predefined objects.
3. To improve security and ease of administration by using object-based configurations that expand dynamically based on their definitions.

**Proposed Solution**
Implement firewall objects as described in the documentation. This includes two main types of objects: `host set` and `domain set`, with each supporting both IPv4 and IPv6 addresses. These objects will be used within firewall rules and other configurations to reference sets of IP addresses or DNS names.
DHCP reservations, DNS records and OpenVPN users with a reservation are parts of the objects.

**Key Elements:**

1. **Host Sets**:
   - Represent sets of IP addresses.
   - Can include single IPs, CIDR networks, ranges, DHCP reservations, domain names, and VPN users.
   - Support both IPv4 and IPv6.

2. **Domain Sets**:
   - Represent sets of DNS names resolved to IP addresses.
   - Include a timeout for DNS resolution.
   - Support both IPv4 and IPv6.

3. **Usage in Rules**:
   - Firewall rules, port forwards, multiwan rules, and DPI rules can reference these objects.
   - Fields such as `ns_src` and `ns_dst` will be used to specify source and destination objects.
   - Automatically update and manage IP sets based on object definitions.
**Additional Context**
- Known limitations of fw4:
  1. A rule can only use one ipset for either source or destination, not both.
  2. Ipsets cannot contain entries with different timeouts.
  3. Rules cannot match both an IP address and a MAC address simultaneously.

**Comment by gsanchietti** [comment]
### 1. Cron Job for Domain Sets
- [ ] **Test Case 1.1:** Verify cron job runs at the specified interval.
- [ ] **Test Case 1.2:** Verify cron job handles errors gracefully.

### 2. Update APIs for Firewall
- [ ] **Test Case 2.1:** Verify updating firewall rules via API.

### 3. Update APIs for Redirects
- [ ] **Test Case 3.1:** Verify updating redirects via API.

### 4. Update APIs for MultiWAN
- [ ] **Test Case 4.1:** Verify updating MultiWAN settings via API.

### 5. Add New APIs for Suggestions
- [ ] **Test Case 5.1:** Verify adding suggestions for firewall via API.
- [ ] **Test Case 5.2:** Verify adding suggestions for MultiWAN with single IP.
- [ ] **Test Case 5.3:** Verify adding suggestions for redirects with single IP.

### 6. Manage Objects APIs
- [ ] **Test Case 6.1:** Verify creating a domain set.
- [ ] **Test Case 6.2:** Verify editing a domain set.
- [ ] **Test Case 6.3:** Verify deleting a domain set.
- [ ] **Test Case 6.4:** Verify creating a host set.
- [ ] **Test Case 6.5:** Verify editing a host set.
- [ ] **Test Case 6.6:** Verify deleting a host set.

### 7. Validate Nested Host-Set
- [ ] **Test Case 7.1:** Verify validation of nested host-set to avoid recursion.

### 8. MultiWAN Single Element Host Set
- [ ] **Test Case 8.1:** Verify allowing host set with a single element in MultiWAN.

### 9. Prevent Deletion if Used
- [ ] **Test Case 9.1:** Verify prevention of deletion if domain/host set is in use.
- [ ] **Test Case 9.2:** Verify prevention of deletion if DHCP/domain record is in use.
- [ ] **Test Case 9.3:** Verify prevention of deletion if VPN user is in use.
- [ ] **Test Case 9.4:** Verify prevention of deletion of objects used inside host sets.

### 10. Host Set
- [ ] **Test Case 10.1:** Verify IPv4 host set with single IP.
- [ ] **Test Case 10.2:** Verify IPv4 host set with CIDR network.
- [ ] **Test Case 10.3:** Verify IPv4 host set with IP range.
- [ ] **Test Case 10.4:** Verify IPv4 host set with DHCP reservation.
- [ ] **Test Case 10.5:** Verify IPv4 host set with DNS name.
- [ ] **Test Case 10.6:** Verify IPv4 host set with VPN user.
- [ ] **Test Case 10.7:** Verify IPv6 host set with single IP.
- [ ] **Test Case 10.8:** Verify IPv6 host set with CIDR network.
- [ ] **Test Case 10.9:** Verify IPv6 host set with IP range.

### 11. Domain Set
- [ ] **Test Case 11.1:** Verify creating domain set with DNS names.
- [ ] **Test Case 11.2:** Verify domain set DNS resolution timeout.

### 12. Rules and Objects
- [ ] **Test Case 12.1:** Verify using domain set in firewall rule as ns_src.
- [ ] **Test Case 12.2:** Verify using host set in firewall rule as ns_dst.
- [ ] **Test Case 12.3:** Verify using static lease in firewall rule.
- [ ] **Test Case 12.4:** Verify using DNS name in firewall rule.
- [ ] **Test Case 12.5:** Verify using VPN user in firewall rule.
- [ ] **Test Case 12.6:** Verify using domain set in port forward as ns_src.
- [ ] **Test Case 12.7:** Verify using single IP object in port forward as ns_dst.
- [ ] **Test Case 12.8:** Verify using domain set in MultiWAN rule as ns_dst.
- [ ] **Test Case 12.9:** Verify using single IP object in MultiWAN rule as ns_src.
- [ ] **Test Case 12.10:** Verify using host set in DPI rule.
- [ ] **Test Case 12.11:** Verify using domain set in DPI rule.

**Comment by cotosso** [comment]
> ### 1. Cron Job for Domain Sets
> * [ ]  **Test Case 1.1:** Verify cron job runs at the specified interval.

**Verified**
crontab line:
`*/10 * * * * /usr/bin/ns-objects-reload-dns`

logs:
`Jul  8 15:10:00 NethSec-box crond[12923]: USER root pid 15752 cmd /usr/bin/ns-objects-reload-dns
Jul  8 15:10:00 NethSec-box crond[12923]: USER root pid 15753 cmd sleep $(( RANDOM % 60 )); /usr/sbin/send-heartbeat
`

> ### 2. Manage Objects APIs
> * [ ]  **Test Case 2.1:** Verify creating a domain set.
> * [ ]  **Test Case 2.2:** Verify editing a domain set.
> * [ ]  **Test Case 2.3:** Verify deleting a domain set.
> * [ ]  **Test Case 2.4:** Verify creating a host set.
> * [ ]  **Test Case 2.5:** Verify editing a host set.
> * [ ]  **Test Case 2.6:** Verify deleting a host set.

**Verified**

**Comment by filippocarletti** [comment]
### nft ruleset not updated after object change
Steps to reproduce:
1. make sure to have at least two objects (any kind)
2. create a rule using object A
3. change the rule using object B
Actual result: nft list ruleset still shows the rule using object A
`service firewall restart` fixes the ruleset
Expected result: ruleset update, without the need for an extra firewall restart

**Comment by cotosso** [comment]
All these cases are **verified**
> ### 5. Prevent Deletion if Used
> * [ ]  **Test Case 5.1:** Verify prevention of deletion if domain/host set is in use.
> * [ ]  **Test Case 5.2:** Verify prevention of deletion if DHCP/domain record is in use.
> * [ ]  **Test Case 5.3:** Verify prevention of deletion if VPN user is in use.
> * [ ]  **Test Case 5.4:** Verify prevention of deletion of objects used inside host sets.

**Comment by gsanchietti** [comment]
@cotosso found this bug:
1. create 2 hosts sets h1 with IP 2.2.2.2 and h2 with IP 3.3.3.3, do not commit changes
2. create a rule using h1 as source and h2 as destination

Expected behavior: the generated rule must match 2.2.2.2 as source and 3.3.3.3 as destination
Actual behavior: the rule uses 3.3.3.3 both as source and destination

This will be added to the test cases after the fix, other test cases can proceed.

**Comment by cotosso** [comment]
All cases **Verified**

All host sets created are consistent and well created both in IPv4 and IPv6.
Host sets with DHCP reservations, DNS records and VPN users are correctly referenced with respect to the source databases.

> ### 6. Host Set
> * [ ]  **Test Case 6.1:** Verify IPv4 host set with single IP.
> * [ ]  **Test Case 6.2:** Verify IPv4 host set with CIDR network.
> * [ ]  **Test Case 6.3:** Verify IPv4 host set with IP range.
> * [ ]  **Test Case 6.4:** Verify IPv4 host set with DHCP reservation.
> * [ ]  **Test Case 6.5:** Verify IPv4 host set with DNS name.
> * [ ]  **Test Case 6.6:** Verify IPv4 host set with VPN user.
> * [ ]  **Test Case 6.7:** Verify IPv6 host set with single IP.
> * [ ]  **Test Case 6.8:** Verify IPv6 host set with CIDR network.
> 

```
config host 'ns_5c43b376'
        option name 'src5'
        option family 'ipv4'
        list ipaddr '10.22.33.44'

config domain 'ns_a4ba92cd'
        option name 'domain1'
        option family 'ipv4'
        option timeout '660'
        list domain 'facebook.com'

config host 'ns_94321cbd'
        option name 'cidr1'
        option family 'ipv4'
        list ipaddr '10.20.30.0/24'

config host 'ns_86822920'
        option name 'iprange1'
        option family 'ipv4'
        list ipaddr '10.40.50.10-10.40.50.20'

config host 'ns_b28847f4'
        option name 'singolohostv6'
        option family 'ipv6'
        list ipaddr '2001:0db8:85a3:0000:0000:8a2e:0370:7334'

config host 'ns_abf9b316'
        option name 'cidrv6'
        option family 'ipv6'
        list ipaddr '2001:0db8:85a3:0000::/64'

config host 'ns_63746405'
        option name 'rese'
        option family 'ipv4'
        list ipaddr 'dhcp/ns_20d6c9e6'

config host 'ns_26d4f539'
        option name 'nome'
        option family 'ipv4'
        list ipaddr 'dhcp/ns_b9410485'

config host 'ns_ba9e384b'
        option name 'vpnuser'
        option family 'ipv4'
        list ipaddr 'users/ns_4e3193c0'
```

**Comment by gsanchietti** [comment]
Test cases 7 verified by @francio87

**Comment by Tbaile** [comment]
Test cases 8 are verified.
