### ISSUE TITLE
Connections management page

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#568]
**Why is this feature being requested?**
1. To provide users with an intuitive interface for managing active network connections tracked by conntrack.
2. To enhance the ability to monitor and control network connections in real-time.
3. To simplify the process of terminating unwanted or problematic connections, improving network security and performance.

**Proposed Solution**
Implement a "Connections Management" page within the firewall section of the interface, with the following functionalities:

1. **Refresh Page**: A button to refresh the page and update the list of current connections.
2. **Delete Single Connection**: An option to delete individual connections, allowing users to terminate specific connections that are suspicious or unnecessary.
3. **Delete All Connections**: A feature to delete all current connections, providing a quick way to reset the network state.

**Key Elements:**
- A filter and search option to easily locate specific connections based on criteria such as protocol, status, or IP addresses.
- Columns displaying details of each connection, including Source, Destination, Protocol, Download/Upload, Status, WAN, Timeout, and Duration.
- Action buttons for each connection to delete it individually.
- A global action button to delete all connections.
- A page refresh button to update the connection list.

**Alternative Solutions**
- Use command-line tools to manage connections manually, which is less user-friendly and more time-consuming.

**Additional Context**
- This feature aims to enhance the user experience by providing a graphical interface for managing network connections efficiently.
- The ability to filter and search through connections helps in quickly identifying and managing specific network issues.

**See also**
- Mockup: https://www.figma.com/design/FhVUA3F59rOsQPh2bDlZ7V/Nethsecurity-shared-file?node-id=2030-186529&t=phHGL80xiKobGYAO-4
- Library implementation: https://github.com/NethServer/python3-nethsec/pull/51
- Backend implementation: https://github.com/NethServer/nethsecurity/pull/595

**Comment by gsanchietti** [comment]
Testing image: 23.05.3-ns.1.0.1-55-g831860d

**Comment by stephdl** [comment]
QA

the UI provide a new menu `Firewall > Connections`, it will serve to manage the connection tracking of the linux kernel.

the QA is here to track the issues or misunderstood behaviors of the UI and issues of the API

the table list the connections, with a delete button for each connection, no issue expected
you have two buttons, no issue expected : refresh and delete all connection

when the connections are deleted, a toaster in a upper right must confirm the delete action and the page is refreshed to load again the connections.

**Comment by gsanchietti** [comment]
Verified: the listed connections matches the ones on the kernel, tested also filtering and delete.
