### ISSUE TITLE
Ipsec tunnel not working if selected WAN is a PPPoE over vlan

### ISSUE THREAD

**Issue by cotosso** [NethServer/nethsecurity#571]
**Steps to reproduce**

- create a vlan device 
- configure the vlan device with role WAN in PPPoE
- connect it to a valid provider and receive an ip address 
- configure an ipsec tunnel with this specific WAN

**Expected behavior**

IPsec tunnel works flawlessy

**Actual behavior**

*  Web UI shows IPsec tunnel connected, but traffic doesn't flow
* ipsecX interface is not present (tested with _ip a_ command and _ifconfig_)

**Components**

NethSecurity 8-23.05.3-ns.1.0.0

**Comment by cotosso** [comment]
After some test I found in the network database a missing reference

`network.ipsec1.tunlink='None'`

whereas this field should have the WAN interface name.
So i  set this parameter with the right value e.g.

`network.ipsec1.tunlink='Irideos'`

and then everything started to work as expected.

I'm not able to verify if the the problem occurs only for PPPoE **over  a vlan** or also for PPPoE over other devices (e.g. physical, bond...)

**Comment by mamengoni** [comment]
tested and verified!
