### ISSUE TITLE
Expose admin users

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#575]
A local user inside the `users` database can be converted to a local admin using the `ns.users set-admin` API.

To revoke the admin access, use the `ns.users remove-admin` API.

‌
Expose the function inside the User database page.

**Comment by gsanchietti** [comment]
Testing image: [8-23.05.3-ns.1.0.1-10-g168db29](https://updates.nethsecurity.nethserver.org/dev/8-23.05.3-ns.1.0.1-10-g168db29/targets/x86/64/nethsecurity-8-23.05.3-ns.1.0.1-10-g168db29-x86-64-generic-squashfs-combined-efi.img.gz)

**Comment by cotosso** [comment]
It works as expected
```
root@NethSec:~# echo '{ "database": "main"}' |  /usr/libexec/rpcd/ns.users call list-users | jq
{
  "users": [
    {
      "local": true,
      "database": "main",
      "name": "davide",
      "password": "$6$856dcb83e49581c3$R8dtJEEeOOdtr9Bvx0W5P0ub3C8OYNyY.xGoRTTdq3cB8Ghub0c8hNx2tN1myWDvelRGXvKlELLWLvFYiBfdz1",
      "description": "davide",
      "admin": true,
      "id": "ns_0fdab136"
    }
```
