### ISSUE TITLE
MultiWAN: add sticky option in rules

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#581]
On multiwan UI, it would be useful to have the sticky option available in the rules drawer.
This option is tipically used with https traffic and ensures persistence of connections on the same WAN (e.g., to prevent WAN switching when connecting to banks and/or similar services), it has a default timeout of 10 minutes.

![Image](https://github.com/NethServer/nethsecurity/assets/7226896/a5abf4c4-80aa-4e96-b2f6-595926ac5048)

Default value: sticky disabled
tooltip suggestion:  Allow traffic from the same source IP address to use same WAN interface as prior session (default timeout: 10 minutes).

**Comment by gsanchietti** [comment]
Testing image: [8-23.05.3-ns.1.0.1-10-g168db29](https://updates.nethsecurity.nethserver.org/dev/8-23.05.3-ns.1.0.1-10-g168db29/targets/x86/64/nethsecurity-8-23.05.3-ns.1.0.1-10-g168db29-x86-64-generic-squashfs-combined-efi.img.gz)

**Comment by stephdl** [comment]
QA

use the test image

use a multi wan configuration, create a deafault policy, then create a rule, you have a sticky option with a toggle

verify the sticky option is propagated to the CLI, you can enabled and disabled

echo '{}' | /usr/libexec/rpcd/ns.mwan call index_rules | jq

**Comment by cotosso** [comment]
Tested and working as expected, rule created from web UI.
```
root@NethSec:~# echo '{}' | /usr/libexec/rpcd/ns.mwan call index_rules | jq
{
  "values": [
    {
      "name": "ns_rule1",
      "policy": {
        "name": "ns_test1",
        "label": "test1"
      },
      "label": "rule1",
      "protocol": "tcp",
      "destination_port": "443",
      "sticky": true
    },
    {
      "name": "ns_default_rule",
      "policy": {
        "name": "ns_default",
        "label": "Default"
      },
      "label": "Default Rule",
      "sticky": false
    }
  ]
}
```
