### ISSUE TITLE
Restore: show a validation error for invalid passphrase

### ISSUE THREAD

**Issue by andre8244** [NethServer/nethsecurity#587]
Show a validation error "Invalid passphrase" if the user enters a wrong passphrase when restoring a backup.
At the moment the standard toast notification for API failed is shown.

**Comment by stephdl** [comment]
QA

install the test image

go to backup and restore, do a backup with password

try to restore it, the error form of validation must be different if you give no password or if you give a wrong password

**Comment by gsanchietti** [comment]
Testing image: 23.05.3-ns.1.0.1-11-g7926d6e

**Comment by gsanchietti** [comment]
The error is displayed correctly only when restoring a backup with an upload: verified.
If machine has a subscription, and the backup is restored from a remote backup, the old behavior is still present: not verified.

Screenshot of failed verification:
![image](https://github.com/NethServer/nethsecurity/assets/804596/b14219cc-73dd-4960-9845-89ca01603a4f)

**Comment by gsanchietti** [comment]
Now the message is correctly displayed also when restoring a remote backup.

Verified.
