### ISSUE TITLE
User's display name disappears after a VPN account is created

### ISSUE THREAD

**Issue by cotosso** [NethServer/nethsecurity#592]
**Steps to reproduce**

- Add a user to local database, specify the Display Name 
- configure a roadwarrior server working on local database
- Add an account linked to the previously created user

**Expected behavior**

VPN account is created, nothing changes in the user's database 

**Actual behavior**

VPN account is created, display name for the associated user is now missing in local database.

**Components**

NethSecurity 8-23.05.3-ns.1.0.1-10-g168db29 r23809-234f1a2efa

**Comment by stephdl** [comment]
when you create the server with previous existing user, the bulk importation does not break the displayname in the local database
when you create a user after the installation and you import it in the vpn menu then it does not break the display name in the local database

set verified
