### ISSUE TITLE
Freezes at startup

### ISSUE THREAD

**Issue by mrkaban** [NethServer/nethsecurity#600]
This is a vmware virtual machine, converted img, as indicated in your instructions. It starts and hangs on the "device br-lan entered promiscuous mode". You can click enter and log in, but it looks very much like some processes have not completed, since the DHCP interfaces have not received network settings. I read the documentation and tickets here, but I didn't find anything about it.
![0-1](https://github.com/NethServer/nethsecurity/assets/14289360/8700b358-886b-417c-acbe-33ddb436b48f)

**Comment by filippocarletti** [comment]
Did you try pressing the Enter key on your keyboard?
Please, move your support request to https://community.nethserver.org/c/support/

**Comment by mrkaban** [comment]
I get it =\ thank you for your help =\ and thank you for this "wonderful" product.

**Comment by filippocarletti** [comment]
Oops, sorry. :-)
AFAIK, interfaces use DHCP only in KVM (not vmware).
If you ask in the community forum you may find many people with vmware experience.
