### ISSUE TITLE
DPI signatures for community subscriptions

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#603]
Provide updated DPI signatures for both community and enterprise subscription types, ensuring all users have access to the latest DPI data.

**Required changes**

1. Provide access to udated DPI signatures: enable updates for both community and enterprise subscriptions.
2. Setup new Base URLs for uthentication:
     Enterprise:
     ```
     curl -vL 'https://user:pass@sp.nethesis.it/enterprise/'
     ```
    Community:
     ```
     curl -vL 'https://user:pass@sp.nethesis.it/community/'
     ```

Changes to ns-dpi package:
   - modify the package to support the new base URLs for fetching DPI signatures
   - ensure authentication mechanisms are in place to handle both subscription types

Example: download categories:
```
curl -vL 'https://system_id:system_secret@sp.nethesis.it/community/categories?settings_version=4.4.3&settings_format=netifyd'
```

**Comment by gsanchietti** [comment]
**Test case 1**

- Install a clean machine
- Register the machine with a community subscription
- Verify the machine can see all signatures from the DPI page (check if NordVPN application is enabled)

**Test case 2**

- Install a clean machine
- Register the machine with an enterprise subscription
- Verify the machine can see all signatures from the DPI page (check if NordVPN application is enabled)

**Test case 1**

- Install a machine using an older images
- Register the machine with an enterprise subscription
- Update the machine
- Verify the machine can still see all signatures from the DPI page (check if NordVPN application is enabled)

**Comment by Tbaile** [comment]
- [ ] Test case 1
- [ ] Test case 2
- [ ] Test case 3
