### ISSUE TITLE
mwan: increase metrics between interfaces on mwan creation

### ISSUE THREAD

**Issue by Tbaile** [NethServer/nethsecurity#605]
While this is more a QoL improvement, filling a bug explains better the test cases.

---

**Steps to reproduce**

- create a policy within mwan

**Expected behavior**

- interface metrics should be separated by intervals of 10, starting from 20

**Actual behavior**

- interface metrics are starting from 1 then increasing by 1

**Components**

- `python3-nethsec`: 0.0.61

---

Expect that current implemented MWANs to be not updated, this fix will be just for the new creations.

Refs: 
 - https://github.com/NethServer/python3-nethsec/pull/55

**Comment by cotosso** [comment]
Everything works as expected
