### ISSUE TITLE
Wrong label "balance" instead of "custom" in multiwan

### ISSUE THREAD

**Issue by Tbaile** [NethServer/nethsecurity#606]
**How to reproduce**
Create a Multiwan policy with one gateway only (you need to select "custom" from the radio button)

**What expected**
Once the policy has been created the UI will list it with the label and icon of _custom_

**What happen**
The UI shows the policy with the label and icon of _balance_

![Image](https://github.com/NethServer/nethsecurity/assets/7226896/508e57af-e6e6-4253-9863-d9738bcf86de)

---

Refs:
 - backend: https://github.com/NethServer/python3-nethsec/pull/56

**Comment by gsanchietti** [comment]
Testing image version: [8-23.05.3-ns.1.0.1-28-gf93490f](https://updates.nethsecurity.nethserver.org/dev/8-23.05.3-ns.1.0.1-28-gf93490f/targets/x86/64/nethsecurity-8-23.05.3-ns.1.0.1-28-gf93490f-x86-64-generic-squashfs-combined-efi.img.gz)

**Comment by cotosso** [comment]
Everything works as expected
