### ISSUE TITLE
Migration:  user import regression with remote AD

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#609]
**Description:**
Regression bug with user import when using a remote AD Account Provider on NS7.

**Details:**
- **Issue:** Users imported as local database with remote AD (tested with WS22).
- **Working:** Remote LDAP (NS7.9) functions correctly.
- **Discussion:** https://mattermost.nethesis.it/nethesis/pl/jcgefpkacpf8xxx53rt1ebxnnc

**Expected Outcome:**
Users should not be imported as local when using remote AD.

**Actual Outcome:**
Users are imported as local.

This regression was introduced with https://github.com/NethServer/nethsecurity/issues/559

**Comment by gsanchietti** [comment]
Testing package: nethserver-firewall-migration-0.0.18-1.1.g9eb5670.ns7.noarch.rpm

**Test case**

- Check the issue is not reproducible

**Comment by francio87** [comment]
Confirm Fixed,  users are no longer being imported as local
