### ISSUE TITLE
Scheduled System Update: Cosmetic Issue

### ISSUE THREAD

**Issue by Tbaile** [NethServer/nethsecurity#610]
**Steps to reproduce**

- Schedule an update through the UI, then wait for it to apply

**Expected behavior**

- Once updated, the schedule from the UI disappears

**Actual behavior**

- The scheduled update still is displayed through the UI (also the cron for `root`)

```
root@fw:~# cat /etc/crontabs/root 
...
...
8 4 * * * sleep $(( RANDOM % 3600 )); /usr/sbin/dpi-update
20 16 20 06 2024 /usr/sbin/ns-upgrade
```

![Image](https://github.com/NethServer/nethsecurity/assets/42090061/12df2f20-7402-4fc3-a8a0-8295db6b4327)

**Components**

- NethSecurity <= `8-23.05.3-ns.1.0.1`

**REFS**
- https://github.com/NethServer/nethsecurity/pull/611

----

**NOTE**: Due to the fix requiring a uci default, it's probably going to get fixed with a `patch` nethsecurity release.

**Comment by gsanchietti** [comment]
Testing image: 23.05.3-ns.1.0.1-36-gcb03939

**Comment by gsanchietti** [comment]
Verified: the cron is not present after the image upgrade
