### ISSUE TITLE
Proxy pass: WebTop does not work

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#622]
After a migration from NS7 to NS8, a proxy pass to WebTop does not work anymore: the client is redirect to `https://127.0.0.1/webtop/;jsessionid=FE16465413BF5CFA9A4F38D39230D2BF` upon login and logout.

**How to manually fix it**
1. Configure the proxy pass as follows:
    - Type: Domain
    - Host: webtop.nethesis.it
    - Destination: https://192.168.122.59/
2. Locate the `location` type record in `/etc/config/nginx`
3. Remove the extra header and apply the configuration:
   ```
   uci del_list nginx.<id>.proxy_set_header='X-Forwarded-Proto $scheme'
   uci commit nginx
   /etc/init.d/nginx restart
   ```
4. Access webtop using: `https://webtop.nethesis.it/webtop` (note /webtop at the end)

**Proposed changes**
Since the bug can't be solved from upstream, change current proxy pass impelementation and remove the X-Forwarded-Proto : this should eventually improve backward compatibility also with other applications.

References (private):
- https://mattermost.nethesis.it/nethesis/pl/w1an8jefpigb7mahmr43d3yzzh
- https://mattermost.nethesis.it/nethesis/pl/mnbnc1uxkpbgx8rzc8e4bex6er
- https://mattermost.nethesis.it/webtop/pl/qnajpqy4obd13gjkua8mgumuor

**Comment by gsanchietti** [comment]
Testing image: 23.05.3-ns.1.0.1-56-g1d700e8 (https://github.com/NethServer/nethsecurity/actions/runs/9758641733)


**Test case 1**
- Configure a new proxy pass with the configuration reported inside the description
- Check WebTop is recheable, as an alternative check the `X-Forwarded-Proto` header is not set

**Test case 2**
The issue also include another change inside the reverse proxy default: the max body size has been increased from 1MB (default) to 1GB as in NethServer 7.
- Configure a new proxy pass
- Verify the the `client_max_body_size` is configured to `1024MB` inside the location record

**Comment by mamengoni** [comment]
Tested and verified!
