### ISSUE TITLE
Local database users disappears

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#625]
With the latest updates, users in the local database seem to disappear (including OpenVPN users). After the upgrade, /etc/config/users is empty.

Steps to reproduce

 -  Update NethSecurity to the specified versions.
 -  Check /etc/config/users.

Expected behavior

Users in the local database should remain intact after the update.

Actual behavior

Users in the local database disappear, causing issues with OpenVPN user configurations.

Components

On NethSecurity 8-23.05.3-ns.1.0.1:
- ns-objects: 0.0.2-1 to 0.0.3-1
  
See also

https://community.nethserver.org/t/nethsec-missing-users-after-update/23997

**Comment by cotosso** [comment]
I updated to ``ns-objects - 0.0.4-1 - Manage firewall objects and users`` via opkg and the users database is still there with no modifications.
