### ISSUE TITLE
Migration: Wrong OpenVPN-RW account status

### ISSUE THREAD

**Issue by cotosso** [NethServer/nethsecurity#631]
In a migrated environment (from NethSecurity7 to NethSecurity8 with migration tool) OpenVPN RW accounts are working but they always display *disconnected* status even though they are connected.

**Steps to reproduce**

- Configure a NethSecurity 7 with OpenVPN RW (local or external database)
- Make sure OpenVPN server is configured to authenticate certificate-only or user+password+certificate
- Migrate NethSecurity7 to NethSecurity 8 with export file (it should be the same for an inplace migration)

The issue is not reproducible with username+password or OTP authentications.

**Expected behavior**
OpenVPN account's status reflects the right connection status

**Actual behavior**
Migrated OpenVPN account continue working but its displayed status is always disconnected.

**Components**

NethSecurity 8-23.05.3-ns.1.0.1-70-g9ef0f6b
NethServer7 migration package: nethserver-firewall-migration-0.0.19-1

**Comment by gsanchietti** [comment]
Verified
