### ISSUE TITLE
OpenVPN tunnel server: add option "remote-cert-tls" in exported file

### ISSUE THREAD

**Issue by Tbaile** [NethServer/nethsecurity#633]
**How to reproduce:**

- go to OpenVPN Tunnel, server section
- create a tunnel server with standard options
- Download the client configuration file
- Import the file on the client
- client’s logs will show the warning  (_WARNING: No server certificate verification method has been enabled.  See_ [http://openvpn.net/howto.html#mitm](http://openvpn.net/howto.html#mitm "smartCard-inline")  _for more info.)_

because the clinet configuration is missing the following option

```
remote-cert-tls server
```

this way the client continues to show the WARNING even though the certificate has EKU.

REF:
- #634

**Comment by Tbaile** [comment]
Test case (using two firewalls in the same RED network): 
- Create a OpenVPN server in the server firewall
- Download the configuration and import it in the client
- Ensure that in the client there's no log line about `WARNING: No server certificate verification method has been enabled.`

**Comment by gsanchietti** [comment]
The warning is gone when using the new JSON file.

Verified.
