### ISSUE TITLE
Cannot create reverse proxies with nginx

### ISSUE THREAD

**Issue by Tbaile** [NethServer/nethsecurity#646]
**Steps to reproduce**

- create a reverse proxy

**Expected behavior**

- nginx creates a reverse proxy without issues

**Actual behavior**

- nginx fails to validate configuration, output below:
```
Jul 15 14:41:17 dum-machine nginx_init: 2024/07/15 14:41:17 [emerg] 4212#0: "client_max_body_size" directive invalid value in /etc/nginx/conf.d/ns_8647759a.proxy:8
Jul 15 14:41:17 dum-machine nginx_init: nginx: configuration file /etc/nginx/uci.conf test failed
Jul 15 14:41:17 dum-machine nginx_init: NOT using conf file!
```

**Components**

- `python3-nethsec >= 0.0.65`

**See also**

Internal discussion: https://mattermost.nethesis.it/nethesis/pl/d9jymzg18ide9dpexogrct1w1w

----

Fix Ref:
- https://github.com/NethServer/python3-nethsec/pull/60

**Comment by Tbaile** [comment]
Test cases:
- create a reverse proxy
- ensure that `client_max_body_size` of said reverse proxy has the `1024m` value
- commit changes
- ensure that `api-cli ns.reverseproxy check-config` after the commit does returns a success

**Comment by gsanchietti** [comment]
To inspect if there is a problem with the config, use this command: ` /usr/sbin/nginx -c /etc/nginx/uci.conf -T`

Output example:
```
2024/07/16 07:04:19 [emerg] 11544#0: "client_max_body_size" directive invalid value in /etc/nginx/conf.d/_lan.proxy:8
nginx: configuration file /etc/nginx/uci.conf test failed
```

To fix an existing machine, use this command:
```
 sed -Ei "s/([0-9]+)MB'$/\1m'/" /etc/config/nginx
 /etc/init.d/nginx restart
```

To force the update on a machine with subscription:
```
cp /etc/opkg/distfeeds.conf /etc/opkg/distfeeds.conf.ori
cat /rom/etc/opkg/distfeeds.conf | sed 's/dev/stable/g' > /etc/opkg/distfeeds.conf
opkg update
/bin/opkg list-upgradable | /usr/bin/cut -f 1 -d ' ' | /usr/bin/xargs -r opkg upgrade
mv /etc/opkg/distfeeds.conf.ori /etc/opkg/distfeeds.conf
```
