### ISSUE TITLE
Limit interface names to 13 characters

### ISSUE THREAD

**Issue by Tbaile** [NethServer/nethsecurity#650]
When creating a mwan with a interface that exceeds 13 characters in the name, iptables associated to the mwan fails to be applied and mwan won't work (it will silently fail, can be noted through logs)

Solution is to limit further the naming for the interfaces in the firewall, limiting them to only 13 characters long.

**Steps to reproduce**

- create a RED interface with > 13 characters
- associate the interface to a mwan

**Expected behavior**

- mwan will work as planned, no log ouput

**Actual behavior**

- mwan will actually confirm the creation, however something like this will pop up in the log
```
mwan3-hotplug[6711]: create_iface_iptables (<interface_name>): iptables-restore v1.8.8 (legacy): chain name `mwan3_iface_in_<interface_name>' too long (must be under 29 chars)#012Error occurred at line: 2#012Try `iptables-restore -h' or 'iptables-restore --help' for more information.
```

**Components**

- `ns-ui: 1.0.13`

**See also**

Internal discussion: https://mattermost.nethesis.it/nethesis/pl/rokefgpm83r7zmbeyrhobnazgo

**Comment by Tbaile** [comment]
Test cases:
- Create a RED interface with a name greater than 13 characters, ensure it's not possible to create one
- Create a MWAN with said interface, ensure after the commit that `mwan3-hotplug` does not return the iptables error

**Comment by gsanchietti** [comment]
Verified: the name of new interfaces can't be longer than 13 chars, the length is good for creating iptables mwan rules.
