### ISSUE TITLE
OpenVPN: unable to uemove ueserved IP for Road Warrior client

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#661]
**Description**

It is currently not possible to remove the reserved IP for a Roadwarrior client. Clearing the field and saving does not remove the IP, while modifications are correctly applied.

**Steps to reproduce**

1. Access the Road Warrior client configuration page.
2. Attempt to remove the reserved IP by clearing the IP field.
3. Save the changes.
4. Observe that the reserved IP is not removed.

**Expected behavior**

The reserved IP should be removed when the IP field is cleared and changes are saved.

**Actual behavior**

The reserved IP remains even after the IP field is cleared and changes are saved.

**Components**

ns- ui - 1.0.20-1
n-api 0.0.81-1

**Comment by cotosso** [comment]
The proposed fix works as expected. now it's possible to remove the reserved ip address.
