### ISSUE TITLE
Remote backup for all subscriptions

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#664]
**Overview:**
Extend remote backup access to both Enterprise and Community subscriptions. Additionally, provide more detailed information about each backup and expose the delete backup functionality.

**Details:**
- **Extended Access:** Enable remote backup functionality for both Enterprise and Community subscriptions.
- **Additional Information:** Expose the following additional details for each backup:
  - **Creation Date:** Display the creation date in local time.
  - **Encryption Status:** Indicate whether the backup is encrypted or not.
  - **Size:** Show the size of each backup.

**Required Changes:**
1. **Backend:**
   - Modify the remote backup service to allow access for Community subscriptions.
   - Update the API to include the additional information (creation date, encryption status, size).

2. **Frontend:**
   - Display the creation date in local time for each backup entry.
   - Indicate whether the backup is encrypted.
   - Show the size of each backup.
   - Add a delete button to the backup list, enabling users to delete backups.

**Benefits:**
- **Inclusivity:** Community subscription users will now have access to remote backup, increasing the value of their subscription.
- **Enhanced Usability:** Users will have more detailed information about their backups, aiding in better management.
- **Improved Control:** The delete backup button will allow users to manage their storage more effectively.

**Comment by gsanchietti** [comment]
**Test case 1**

- Install a clean machine without a subscription
- Check the backup page behavior is unchanged, the user must be able to:
  -  download a backup archive
  -  restore an uploaded backup archive

**Test case 2**

- Register the machine with an Enterprise subscription
- Check the backup page behavior is almost unchanged:
  - the user must be able to see the list of existing remote backups
  - the user must be able to download a remote archive
  - the user must be able to restore a remote archive (please verify the restore is successful!)
- Check also the user can delete a remote archive

**Test case 3**

- Register the machine with an Community subscription
- Check the backup page behavior is almost unchanged:
  - the user must be able to see the list of existing remote backups
  - the user must be able to download a remote archive
  - the user must be able to restore a remote archive (please verify the restore is successful!)
- Check also the user can delete a remote archive

**Comment by cotosso** [comment]
Test case  1 and 2 are OK.

Test case 3  (sub community)  : backup page gives this error:

*cannot retrieve backups*

```
root@NethSec:~# /usr/libexec/rpcd/ns.backup call registered-list-backups
Traceback (most recent call last):
  File "/usr/libexec/rpcd/ns.backup", line 161, in <module>
    print(json.dumps({'values': json.loads(completed_process.stdout)}))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by cotosso** [comment]
Now also test case 3 is well managed

**Comment by gsanchietti** [comment]
Some changes have been added to the UI.

**Test case 4**
- Setup a passhphrase
- Check the a banner is displayed
- Disable the passhprase
- Check the banner disappers

**Test case 5**
- From test case 1
- Try to download the backup
- Verify the backup file name has the form  `backup-<hostname>-<creation_timestamp>.<extension>`

**Test case 6**
- From test case 2 or 3
- Try to download the backup
- Verify the backup file name has the form  `backup-<hostname>-<creation_timestamp>.<extension>`

**Test case 7**
- From test case 2 or 3
- Try to download an encrypted backup
- Verify the extension is `.gpg`

**Test case 8**
- From test case 2 or 3
- Try to download a non-encrypted backup
- Verify the extension is `.tar.gz`

**Comment by gsanchietti** [comment]
Test image: 23.05.3-ns.1.1.0-71-ge75871e
