### ISSUE TITLE
New script to update packages with logging and stable channel access

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#668]
**Overview:**
Implement a new update-packages script to improve troubleshooting and provide the ability to gather updates from the stable channel regardless of subscription status.

**Features:**
1. **Enhanced Logging:**
   - All operations are logged to syslog and stderr.
   - Useful for troubleshooting and tracking automatic updates.

2. **Force-Stable Flag:**
   - Accepts the `--force-stable` flag to gather updates from the stable channel regardless of subscription status.
   - Useful for quickly distributing fixes.

**Comment by gsanchietti** [comment]
**Test case 1**
- Configure a machine with a subscription and enable automatic updates
- Update an existing machine with the attached packages, upload them to a machine  and install them using this command:
  ```
  opkg install --force-reinstall  ns-api_0.0.83-1_all.ipk ns-plug_0.0.11-1_all.ipk
  ```
- Check the new `update-packages` is invoked inside `/etc/crontab/root`

**Test case 2**
- After test case 1, try to disable the automatic updates from the UI
- Check the `update-packages` is not included inside `/etc/crontab/root`
- Enable the automatic updates from the UI
- Check the `update-packages` is included inside `/etc/crontab/root`

**Test case 3**
- After test case 1, execute package update from UI
- Verify the updates are working and you can see output inside `/var/log/messages`. Output should look like this:
   ```
   Jul 23 09:45:50 NethSec update-packages: Downloading https://updates.nethsecurity.nethserver.org/dev/23.05.3/targets/x86/64/packages/Packages.gz
   Jul 23 09:45:52 NethSec update-packages: Updated list of available packages in /var/opkg-lists/nethsecurity_core
   Jul 23 09:45:52 NethSec update-packages: Downloading https://updates.nethsecurity.nethserver.org/dev/23.05.3/targets/x86/64/packages/Packages.sig
   Jul 23 09:45:52 NethSec update-packages: Signature check passed.
   ...
   ```

**Test case 4**
- Execute the `update-packages` script from command line
- Verify the output is sent to the console and to `/var/log/messages`

**Test case 5**
- Force the update from command line on a subscription machine: `update-packages --force-stable`
- Verify the script grabs packages from the stable channel
- At the end of the script, verify that `/etc/opkg/distfeed.conf` still contains references to the subscription (`grep distfeed.nethesis.it /etc/opkg/distfeed.conf`)

**Comment by Tbaile** [comment]
Test case 1 fails (booting a stable installation, fresh from website, then registering the machine):
```bash
wget https://updates.nethsecurity.nethserver.org/dev/23.05.3/packages/x86_64/nethsecurity/ns-plug_0.0.11-1_all.ipk -O /tmp/ns-plug_0.0.11-1_all.ipk
wget https://updates.nethsecurity.nethserver.org/dev/23.05.3/packages/x86_64/nethsecurity/ns-api_0.0.83-1_all.ipk -O /tmp/ns-api_0.0.83-1_all.ipk
opkg install --force-reinstall /tmp/ns-api_0.0.83-1_all.ipk /tmp/ns-plug_0.0.11-1_all.ipk
cat /etc/crontabs/root | grep update-packages
```
Provides no output, /etc/crontabs/root file:
```
0 */4 * * * sleep $(( RANDOM % 3600 )); /etc/init.d/banip reload
0 0 * * * /etc/init.d/acme start
04 0 * * * /usr/bin/dpireport-cleanup
1 */12 * * * sleep $(( RANDOM % 3600 )); /etc/init.d/adblock reload
10 4 * * * sleep $(( RANDOM % 1800 )); /usr/sbin/send-phonehome
3 3 12 12 * /usr/bin/nginx-util 'check_ssl'
5 1 * * * /usr/sbin/logrotate /etc/logrotate.conf
5 2 * * * sleep $(( RANDOM % 18000 )); /bin/opkg list-upgradable | /usr/bin/cut -f 1 -d ' ' | /usr/bin/xargs -r opkg upgrade
8 4 * * * sleep $(( RANDOM % 3600 )); /usr/sbin/dpi-update
02 2 * * * sleep $(( RANDOM % 1800 )); /usr/sbin/send-backup
*/10 * * * * sleep $(( RANDOM % 60 )); /usr/sbin/send-heartbeat
05 3 * * * sleep $(( RANDOM % 1800 )); /usr/sbin/send-inventory
```

During installation i recieve from `opkg` the following warning:
```
Removing package ns-api from root...
Removing package ns-plug from root...
Installing ns-api (0.0.83-1) to root...
Installing ns-plug (0.0.11-1) to root...
Configuring ns-api.
Configuring ns-plug.
//usr/lib/opkg/info/ns-plug.postinst: .: line 3: can't open '/etc/uci-defaults/20_ns-plug': No such file or directory
```

**Comment by gsanchietti** [comment]
> During installation i recieve from `opkg` the following warning:

This is and indicator that you're installing the wrong package, because the code that executes that command has been removed: https://github.com/NethServer/nethsecurity/commit/681774c70d73db36321f3dcb7ebb39b04f412e7e
