### ISSUE TITLE
Add objects support in MultiWAN rules

### ISSUE THREAD

**Issue by Tbaile** [NethServer/nethsecurity#671]
Ad objects support in MultiWAN UI (rules section).
These are the fields we should cover with objects:

- src addr (accepts only one IP/CIDR)
- dest addr (accepts only one  IP/CIDR)

---

Refs:
- Frontend Implementation: https://github.com/NethServer/nethsecurity-ui/pull/323
- Backend touches: https://github.com/NethServer/nethsecurity/pull/674
- Library implementation: https://github.com/NethServer/python3-nethsec/pull/61
- Adding CIDRs to source and destinations
  - API: https://github.com/NethServer/nethsecurity/pull/707
  - Backend: https://github.com/NethServer/python3-nethsec/pull/63

---

## QA
Case 1:
- Create a MWAN using no objects, ensure creation is successfull and edit is possible.

Case 2:
- Ensure it's not possible to use a domain set as source or destination

Case 3:
- Create a MWAN using a HostSet with a single ip, ensure it's possible to add the HostSet to both source and destination, then try to edit and ensure it's successfull

Case 4: 
- Try to create a MWAN with a multi ip HostSet, ensure that is not possible.

Case 5:
- Create an host set with an IPv6
- Make sure it's not possible to create a rule with such host set

**Comment by Tbaile** [comment]
Testing image: [23.05.4-ns.1.1.99-alpha1-35-g92bbbedc](https://github.com/NethServer/nethsecurity/actions/runs/10245932930/artifacts/1775597282)

**Comment by gsanchietti** [comment]
### Failed Test Cases

1. **Form not cleared when a new rule is added after another one**: The form retains previous inputs when adding a new rule immediately after saving another one.

2. **Selection checkbox is different from rules inside the rules page**: The selection checkbox does not match the rules listed on the rules page.

3. **IPv6 objects should not be supported**: IPv6 objects are being supported when they should not be.

4. **Rule not created when using any object as destination (mwan3)**: MWAN3 does not create a rule when any object is used as a destination.
   ```plaintext
   config rule 'ns_r7'
     option label 'r7'
     option use_policy 'ns_default'
     option sticky '0'
     option proto 'udp'
     option ns_src 'dhcp/ns_6930f270'
     option ns_dst 'objects/ns_8703278a'
     option src_ip '1.2.3.4'
     option ipset 'None dst'
   ```

5. **No domain set as destination**: domain sets are converted to ipset, so they can't be used as destination, see [official doc](https://openwrt.org/docs/guide-user/network/wan/multiwan/mwan3#nft2ipset_init_script)

**Comment by gsanchietti** [comment]
Testing image: https://github.com/NethServer/nethsecurity/actions/runs/10279723774/artifacts/1784490295

**Comment by gsanchietti** [comment]
All test cases are now verified.
Still, I've found the user can create a rule with the same object as source and destination. The same thing is not possible within the firewall rule page.
