### ISSUE TITLE
Firewall rules: zone not exposed in UI in some case

### ISSUE THREAD

**Issue by andre8244** [NethServer/nethsecurity#677]
Zone is not always exposed in the WebUI if a source/destination address is specified.

Edit UI and show the zone badge if user specify a zone in addition to an address or without it.
See mockup as example here and in [Figma file](https://www.figma.com/design/FhVUA3F59rOsQPh2bDlZ7V/Nethsecurity-shared-file?node-id=2127-212503&t=VOfyivxv2ZKDd1UO-0)

![Image](https://github.com/user-attachments/assets/eba89dd8-dd83-47b5-bfbb-e9481eaffb21)

**Comment by andre8244** [comment]
**Test case**
- Go to Firewall > Rules
- Add one or more forward/input/output rules
- The only case the source zone should NOT appear under Source column is when a source address/object is specified AND source zone is "Any"
- The only case the destination zone should NOT appear under Destination column is when a destination address/object is specified AND destination zone is "Any"

**Comment by gsanchietti** [comment]
Verified.
