### ISSUE TITLE
Visual issue with DHCP objects in OpenVPN RoadWarrior

### ISSUE THREAD

**Issue by Tbaile** [NethServer/nethsecurity#680]
**Steps to reproduce**

- Create a OpenVPN RW
- Browse DHCP options of said VPN

**Expected behavior**

- Able to edit those options

**Actual behavior**

- outright missing fields
- if options were already present, [object Object] as field, see below
![image](https://github.com/user-attachments/assets/1e3dd2e9-b003-4018-b941-01cb828bdc05)

**Components**

Regression introduced by `ns-ui: 1.0.14`

**See also**

- Internal discussion: https://mattermost.nethesis.it/nethesis/pl/pbdiidpjstngpp6sxjcfertwur
- Refs:
  - https://github.com/NethServer/nethsecurity-ui/pull/325
  - https://github.com/NethServer/nethsecurity/pull/679

**Comment by gsanchietti** [comment]
Testing image: 23.05.3-ns.1.1.0-83-g4085d1a

**Comment by gsanchietti** [comment]
After the fix the field is displayed correctly.

Verified.
