### ISSUE TITLE
dedalo: update default DNS on chilli.conf template

### ISSUE THREAD

**Issue by cotosso** [NethServer/nethsecurity#681]
This is not a new feature, but a little improvement about DNS server management.
Currently, the default DNS servers of the hotspot service are both from OpenDNS (Cisco).
To increase the robustness of the service and protect yourself in the event of malfunctions or blocks, it is preferable to use different DNS providers.

**Proposed solution**
The providers must be subjects of primary global size, which make their service available for free and which can always ensure a good quality of service.

The proposal is to replace the Opendns DNS servers with a server provided by Google (8.8.8.) and the other provided by Cloudflare (1.1.1.1), incorporating the changes already present in the chilli.conf.tpl file of the icaro project https://github.com/nethesis/icaro

**Comment by gsanchietti** [comment]
The change of default DNS settings wouldn't take effect without extra work.
The extra work isn't justified by the current situation.

DNS can be quickly changed following the [existing documentation](https://docs.nethsecurity.org/en/latest/hotspot.html#change-dns-settings)

Unless there are any reason to update dedalo package, I propose to close this as wontfix.

**Comment by gsanchietti** [comment]
Closing as wontfix.
Please reopen if current default DNS servers are inaccessible from many countries.
