### ISSUE TITLE
 MultiWAN: missing WAN disconnection/reconnection alerts

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#692]
Alerts for WAN disconnection and reconnection events are not being generated.

**Steps to Reproduce:**
1. Connect a router (e.g., an LTE router) to eth0.
2. Power off the router in the evening and power it on in the morning.
3. Check for alerts inside the logs or in the remote portal (my.nethesis.it or my.nethserver.com)

**Observed Behavior:**
- No alerts are received for WAN disconnection/reconnection events.
- The interface shows disconnection in the real-time logs, but no corresponding alert is generated.

**Log Excerpt:**
```
Jul 22 20:56:20 NethSec netifd: Interface 'WAN2' has link connectivity loss
Jul 22 20:56:20 NethSec netifd: Interface 'WAN2' is now down
Jul 22 20:56:20 NethSec mwan3-hotplug[12343]: Execute ifdown event on interface WAN2 (unknown)
Jul 22 20:56:20 NethSec mwan3track[20846]: Detect ifdown event on interface WAN2 (eth0)
Jul 22 20:56:20 NethSec mwan3track[20846]: Interface WAN2 (eth0) is offline
Jul 22 20:56:20 NethSec mwan3-hotplug[12457]: Execute disconnected event on interface WAN2 (eth0)
```

**Expected Behavior:**
- Alerts should be received for WAN disconnection and reconnection events on the MY interface and via email.

**Analysis:**
- The MWAN3 service tracks the WAN's status and records the score in `/var/run/mwan3track/wan2/SCORE`. This file is used by Netdata to send alerts when the score reaches 0.
- When the WAN2 interface goes down, MWAN3 does not update the SCORE file. As a result, Netdata cannot send any alert because the chart does not reflect a change.

**Proposed Solution:**
- Remove the Netdata plugin.
- Use MWAN3 hooks to handle alerting directly.

**Comment by gsanchietti** [comment]
**Test case 1**
- Check the issue is not reproducible


**Test case 2**
- Upgrade an existing machine and reboot
- Verify mwan3 chart is not available inside netdata

**Comment by gsanchietti** [comment]
Removing the testing due because changes to API have caused the regression #697

**Comment by Tbaile** [comment]
Checked both case 1 and 2

Verified.
