### ISSUE TITLE
Update to OpenWrt 23.05.4

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#694]
Bump OpenWrt to 23.05.4.

Official releases notes: https://openwrt.org/releases/23.05/notes-23.05.4

A complete changelog has been generated using `openwrt-changes` tool that can be found inside the `tools` directory of this repository:
```
cd tools && ./openwrt-changes 23.05.3 23.05.4
```
See attached files:
- [core-changes.md](https://github.com/user-attachments/files/16438295/core-changes.md)
- [packages-changes.md](https://github.com/user-attachments/files/16438298/packages-changes.md)

Relevant changes among packages that require extra testing:
- banip
- adblock
- prometheus-node-exporter-lua

Also acme, acme-common, acme-acmesh have been changed but we are using a fork, so we can keep current versions.

Relevant changes at the core level that require extra testing:
- kernel
- openssl

**Comment by gsanchietti** [comment]
Testing image: grab any 8-23.05.4 image from the [download page](https://docs.nethsecurity.org/en/latest/download.html)

**Comment by gsanchietti** [comment]
**Test case 1**

- Install a new machine
- Verify the system starts and main functions are working: UI, firewall rules, DHCP and DNS


**Test case 2**
- Update an existing machine
- Verify the global behavior is unchanged
- Verify all previously recognized hardware is still available

**Test case 3: banip**
- Configure banip from the UI
- Verify that all features are still working

**Test case 4: adblock**
- Configure adblock following the [doc](https://docs.nethsecurity.org/en/latest/threat_shield_dns.html)
- Verify that all features are still working

**Test case 5: prometheus-node-exporter-lua**
- Connect the firewall to a controller
- Verify metrics are still collected from Prometheus
- Verify metrics are visible inside Grafana dashboard

**Comment by cotosso** [comment]
When I try to change the hostname (_nsec8_ is the new name), when I click _save_ button I receive a server error:

```
root@NethSec:~# curl -X POST 'https://192.168.1.1:9090/api/ubus/call' --insecure -H 'Content-Type: application/json' -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyIyZmEiOmZhbHNlLCJhY3Rpb25zIjpbXSwiZXhwIjoxNzIyNjgwMzkzLCJpZCI6InJvb3QiLCJvcmlnX2lhdCI6MTcyMjU5Mzk5Mywicm9sZSI6IiJ9.xNPh6YLdIVzIPyCY--qHeUHxdXLVMUXlxWBY66SBNnI' -d "{\"path\":\"uci\",\"method\":\"set\",\"payload\":{\"config\":\"system\",\"section\":\"@system[0]\",\"values\":{\"hostname\":\"nsec8\",\"zonename\":\"UTC\",\"timezone\":\"\"}}}"
{"code":500,"data":null,"message":"invalid JSON response"}
root@NethSec:~#
```

Said that, if I apply changes from the UI they seems to work correctly.
```
root@NethSec:~# uci show system
system.@system[0]=system
system.@system[0].hostname='nsec8'
```

**Comment by gsanchietti** [comment]
Test cases 1, 2 and 3 verified.

**Comment by gsanchietti** [comment]
Test case 5 verified.

**Comment by gsanchietti** [comment]
Test 4 verified
