### ISSUE TITLE
DHCP and DNS Services for blue/guest zone after migration

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#703]
#### Description:
During migration machine, the blue/guest zone is restored but appears non-functional to users because DHCP and DNS services are closed from the blue/guest network. 

#### Details:
- **Issue**: During migration, the blue/guest zone is restored but appears non-functional due to closed DHCP and DNS services.
- **Current Behavior**: DHCP and DNS services are closed by default for the blue/guest zone, consistent with version 7.
- **Request**: Enable DHCP and DNS services for the  blue/guest zone if it comes from a migration where  blue/guest zone exists.
- **Consideration**: The  blue/guest zone is considered a guest network and not trusted, so only necessary services should be opened.

References:
- https://helpdesk.nethesis.it/a/tickets/179976
- https://mattermost.nethesis.it/nethesis/pl/xpeqbgnootdyjptu9x6k155otw

**Comment by gsanchietti** [comment]
**Test case**

- Configure a NethServer 7 with a blue zone
- Make sure there is at least a client inside the blue zone, the client must use DHCP for network configuration
- Migrate to NethSecurity 8
- Verify the client inside the blue zone can:
  - receive an IP address using the DHCP 
  - access the Internet
  - resolve domain names using the firewall as resolver
- Verify the "Input rules" tab inside the "Rules" page has the following rules:
  
![image](https://github.com/user-attachments/assets/0f348619-abb9-4e96-b6cc-b5396e5ea4dd)

**Comment by cotosso** [comment]
Now rules are recreated in the migrated machine:
![image](https://github.com/user-attachments/assets/ee01f15a-f874-4f74-9810-29f63596852a)

Rules are correctly expanded in the nftables ruleset:
```
      chain input_guest {
                udp dport 53 counter packets 0 bytes 0 accept comment "!fw4: Allow-DNS"
                udp dport 67 counter packets 0 bytes 0 accept comment "!fw4: Allow-DHCP"
                jump reject_from_guest
        }
```

DHCP and DNS are working flawlessy from the GUEST zone.
