### ISSUE TITLE
Limited support for USB-to-Serial adapters

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#711]
USB-to-Serial adapters are often used to connect legacy serial devices to modern systems. This includes scenarios such as:
- Connecting network equipment like routers and switches for configuration and management.
- Integrating legacy industrial control systems.
- Supporting serial communication for specialized hardware in lab or development environments.

To assist with debugging and testing purposes on NethSecurity 8, limited and experimental support for USB-to-Serial adapters will be provided. These adapters are not suitable for production environments due to potential reliability issues. Thus, they will not be included in the NethSecurity image. However, for testing purposes, necessary drivers can be installed manually.

**Supported Devices:**
- Silicon Labs CP210x
- Prolific Technology PL2303

**Proposed Solution:**
- Allow users to download and install the drivers manually via the command line for testing and debugging purposes.
- Clearly document the process for installing the drivers and the limitations of using USB-to-Serial adapters.

**Implementation Steps:**
1. **Driver Distribution:**
   - Make the drivers available for download.
   - Provide detailed instructions for manual installation.

2. **Documentation:**
   - Create documentation outlining the experimental nature of the support.
   - Include step-by-step instructions for downloading and installing the drivers.
   - Highlight that these adapters should not be used in production environments and are not included in the NethSecurity 8 image.
   - Specify that USB-to-Serial adapters are not covered by Nethesis support for enterprise/subscription versions.

**Comment by cotosso** [comment]
Tested with Prolific Technology PL2303:
```
opkg install kmod-usb-serial-pl2303
```

adapter connected:
```
Aug  6 08:08:17 nsec8 kernel: [ 2346.359247] usb 1-6: new full-speed USB device number 3 using xhci_hcd
Aug  6 08:08:17 nsec8 kernel: [ 2346.543052] pl2303 1-6:1.0: pl2303 converter detected
Aug  6 08:08:17 nsec8 kernel: [ 2346.550401] usb 1-6: pl2303 converter now attached to ttyUSB0
```
`lsusb`

```
root@nsec8:~# lsusb
Bus 001 Device 003: ID 067b:2303 Prolific Technology Inc. USB-Serial Controller
Bus 002 Device 001: ID 1d6b:0003 Linux 5.15.162 xhci-hcd xHCI Host Controller
Bus 001 Device 002: ID 8087:0a2a  
Bus 001 Device 001: ID 1d6b:0002 Linux 5.15.162 xhci-hcd xHCI Host Controller
root@nsec8:~# 
```
tested with another appliance via serial console using the command
`screen /dev/ttyUSB0 115200`

everything went fine.
