### ISSUE TITLE
Migration: network configuration not migrated if alias has no gateway

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#716]
The network configuration does not migrate correctly when an alias without the gateway is configured on the green interface during migration from NethServer 7.

**Steps to Reproduce:**
1. Configure a NethServer 7 system with a bridge on the LAN (green interface).
2. Add an alias to the green interface without specifying a gateway.
3. Export the configuration.
4. Import the configuration into NethSecurity 8.
5. Perform the network interface remapping.

**Expected Behavior:**
The network configuration, including the alias, should be migrated to NethSecurity 8 without errors.

**Actual Behavior:**
The network configuration fails to migrate. An error is encountered, and the alias is not created.

**Error:**
```
Creating alias al_br01
Traceback (most recent call last):
  File "/usr/share/ns-migration/20network", line 230, in <module>
    if a["gateway"]:
       ~^^^^^^^^^^^
```

**Additional Information:**
The error occurs because the script attempts to access the "gateway" field for the alias, which does not exist in the provided configuration.

**NethSecurity Version:** 8-23.05.4-ns.1.2.0

**Comment by francio87** [comment]
Confirm, fixed
