### ISSUE TITLE
NAT rules: Add "0.0.0.0/0 Any address"

### ISSUE THREAD

**Issue by andre8244** [NethServer/nethsecurity#720]
Add "0.0.0.0/0 Any address" option among **Destination address** suggestions.

**Comment by andre8244** [comment]
Testing image: https://github.com/NethServer/nethsecurity/actions/runs/10702167669/artifacts/1891101472

**Comment by andre8244** [comment]
**Test case**

Verifiy that "0.0.0.0/0 Any address" appears among **Destination address** suggestions.

**Comment by Tbaile** [comment]
Verified
