### ISSUE TITLE
Report: disable "Open report" button when UI is displayed from the controller

### ISSUE THREAD

**Issue by andre8244** [NethServer/nethsecurity#721]
"Open report"  button in "Report" page is not working when unit UI is accessed from the controller, so the button has to be disabled and show an explanatory tooltip.

**Comment by andre8244** [comment]
Testing image: https://github.com/NethServer/nethsecurity/actions/runs/10702167669/artifacts/1891101472

**Comment by andre8244** [comment]
**Test case**

- Connect the unit to a controller
- Open unit UI from the controller
- Go to **Report** page
- Verify the **Open report** button is disabled and shows an explanatory tooltip on hover

**Comment by Tbaile** [comment]
Verified using controller version [0.0.25](https://github.com/NethServer/ns8-nethsecurity-controller/releases/tag/0.0.25)

**Comment by gsanchietti** [comment]
The release of the "ns8-nethsecurity-controller" update has been suspended due to a compatibility issue identified between the new UI version 1.2.0 and the older version 1.1.0 still in use on many machines.

The update would introduce the 1.2.0 version of the Nethsecurity UI. However, since a significant number of machines are still running version 1.1.0, there is a risk that users accessing these machines via an updated controller might encounter compatibility issues. Specifically, the frontend from version 1.2.0 might attempt to interact with APIs that do not exist in the 1.1.0 backend, potentially leading to errors or malfunctions.

To prevent these issues, the release has been paused until a solution is found to ensure compatibility across the different versions in use.

**Comment by Tbaile** [comment]
Here's the list of what to do to implement Version Awarness for the Controller:

- [X] Add the `UI_VERSION` environment variable in the UI build, so the UI can recognize its version. (from version `1.1.0` of the UI): https://github.com/NethServer/nethsecurity-ui/pull/344
-  [ ] Add the `ns-ui` package version of the unit payload sent to the controller: [`GetUnitInfo`](https://github.com/NethServer/nethsecurity-controller/blob/52fa4858f3b44fbc3c4e65005354c7039e79b9df/api/methods/unit.go#L121). The unit API is `ns.controller` with the method `info`.
    - [ ] Make the VPN perform `GetUnitInfo` directly when the machine connects; otherwise, we cannot perform this check.
        Implement the call via the command line (?), which might be the simplest path (or create a binary that shares the same functionality).

**Comment by Tbaile** [comment]
QA (to be edited when PRs close):
1. Outdated firewall
  - Install the controller using branch version: `add-module ghcr.io/nethserver/nethsecurity-controller:<TBA>`
  - Connect a stable firewall, ensure that's not possible to connect to it, a popup should appear prohibiting to do so
2. Up to date firewall
  - Install the controller using branch version: `add-module ghcr.io/nethserver/nethsecurity-controller:<TBA>`
  - Update a stable firewall using this version: TBA
  - When connecting to the unit through the controller, ensure no popup is visible and the firewall opens correctly
3. Outdated controller
  - Install the controller using branch version: `add-module ghcr.io/nethserver/nethsecurity-controller:<TBA>`
  - Update a stable firewall using this version: TBA
  - MANUAL EDIT: edit the file `/usr/libexec/rpcd/ns.controller` in the unit, at row `67`, replace it's content with the following: 
    ```python
    ret["api_version"] = "1.1.0"
    ```
  - Connect the controller and the unit, ensure that a warning providing info regards of mismatched version appears, HOWEVER it's still possible to connect to the unit through the modal.

**Comment by gsanchietti** [comment]
Test case 1 on report button is verified.

**Comment by gsanchietti** [comment]
Tested with latest image: the error was present only if the "don't show again" option was never clicked.
This case is now handled correctly.

Verified

**Comment by gsanchietti** [comment]
Released version 1.0.0.
