### ISSUE TITLE
 Host-based reverse proxy always accessible from all networks

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#723]
**Description:**

The reverse proxy domain remains accessible from outside the LAN even when the local IP is configured in the "Allowed networks" field. This issue occurs specifically with host-based proxy passes, while path-based proxy passes are not affected.

**Steps to Reproduce:**

1. Configure a host-based proxy pass on NethSecurity 8.
2. Add the local IP to the "Allowed networks" field.
3. Attempt to access the domain from outside the LAN.

**Expected Behavior:**  
The domain should be inaccessible from outside the LAN.

**Actual Behavior:**  
The domain is still accessible from outside the LAN.

**Configuration Example (Incorrect):**
```shell
config server 'ns_eea979ea'
	option proxy_ssl_verify 'off'
	option ssl_session_timeout '64m'
	option ssl_session_cache 'shared:SSL:32k'
	list listen '443 ssl'
	list listen '[::]:443 ssl'
	list include 'conf.d/ns_eea979ea.proxy'
	option access_log 'syslog:server=unix:/dev/log'
	option error_log 'syslog:server=unix:/dev/log'
	option server_name 'ns8.prebrabander.nl'
	option ssl_certificate '/etc/nginx/conf.d/_lan.crt'
	option ssl_certificate_key '/etc/nginx/conf.d/_lan.key'
	option uci_description 'd1'
	list allow '127.0.0.0/24'

config location 'ns_1d57aae6'
	option proxy_http_version '1.1'
	list proxy_set_header 'X-Forwarded-For $proxy_add_x_forwarded_for'
	list proxy_set_header 'X-Real-IP $remote_addr'
	list proxy_set_header 'Upgrade $http_upgrade'
	list proxy_set_header 'Connection "upgrade"'
	list proxy_set_header 'Host ns8.prebrabander.nl'
	option client_max_body_size '1024m'
	option uci_server 'ns_eea979ea'
	option location '/'
	option resolver '127.0.0.1'
	option proxy_pass 'http://$upstream/online/'
	list set '$upstream sublimegrandbrightstars.neverssl.com'
```

- The line `list allow '127.0.0.0/24'` should be placed under `location 'ns_1d57aae6'` instead of under `server 'ns_eea979ea'`.
- A "deny all" rule is added automatically inside the locations, but not on server sections.

**References**

- https://community.nethserver.org/t/allowed-networks-in-reverse-proxy-do-not-work/24362

---

Thanks to **MadPatrick** and **MrMarkus**

**Comment by gsanchietti** [comment]
Testing image: 23.05.4-ns.1.2.0-11-g75fbec65

**Comment by Tbaile** [comment]
QA failed:
1. Can't add an allowed network on reverse proxy path creation (it's possible when editing it)
2. When creating/editing a domain, the allow rule is added correctly but it's not visible through the UI

**Comment by Tbaile** [comment]
Testing version: [23.05.4-ns.1.2.0-14-gad98dcb4](https://github.com/NethServer/nethsecurity/actions/runs/10701988296/artifacts/1891052543)
