### ISSUE TITLE
NAT helpers

### ISSUE THREAD

**Issue by andre8244** [NethServer/nethsecurity#724]
Implement NAT helpers API and UI.

Docs:
- [NAT helpers in admin manual](https://docs.nethsecurity.org/en/latest/nat_helpers.html)
- [NAT helpers in dev manual](https://dev.nethsecurity.org/design/nat_helpers/)

Todo:
- [x] API implementation
- [x] API docs in dev manual
- [x] UI
- [x] Admin manual

**Comment by andre8244** [comment]
**Testing image**

[23.05.4-ns.1.2.0-36-gfcc1f065](https://github.com/NethServer/nethsecurity/actions/runs/10812881491/artifacts/1919729133)

**Test case**
- Go to **Firewall > NAT > NAT helpers**
- Verify that NAT helpers management works as expected

**Comment by andre8244** [comment]
New testing image: [23.05.4-ns.1.2.0-39-g1983cf04](https://github.com/NethServer/nethsecurity/actions/runs/10831739248/artifacts/1924909065)

**Comment by gsanchietti** [comment]
Both test cases have been verified.

**Comment by gsanchietti** [comment]
Released, but we are going to keep the issue open until the documentation is ready.

**Comment by andre8244** [comment]
Image: [23.05.4-ns.1.2.0-40-g53a6a8a1](https://github.com/NethServer/nethsecurity/actions/runs/10833544871/artifacts/1925490658)
