### ISSUE TITLE
Migration: firewall rules not converted to guest zone

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#726]
**Description:**

During the migration from NethSecurity 7.9 to 8, firewall rules with the source or destination set to the `blue` zone are not properly converted to the `guest` zone in NethSecurity 8.

The same issue is reproducible also with rules using `orange` zone which should be converted to `dmz`.

**Steps to Reproduce:**

1. Create firewall rules on NethSecurity 7.9 with the "blue" zone as the source or destination.
2. Migrate the configuration to NethSecurity 8.
3. Check the firewall rules post-migration.

**Expected Behavior:**  
The firewall rules should be converted to use the "GUEST" zone.

**Actual Behavior:**  
The rules remain associated with the "blue" zone instead of being converted to "GUEST."

**Example Configuration (Post-Migration):**
```ini
config rule 'ns_103'
    option proto 'all'
    option dest 'openvpn'
    option src 'blue'
    option name '103_migrated_openvpn'
    option target 'ACCEPT'
    option log '0'
    option enabled '1'
    list dest_ip '192.168.0.251'
    list src_ip '192.168.10.2'
    list ns_tag 'migrated'
```

**Comment by gsanchietti** [comment]
**Test case**

- On NethServer 7, install nethserver-firewall-migration-0.0.20-1.2.gcb8325f.ns7.noarch.rpm from testing repository
- Export the archive
- Import the archive inside the NethSecurity 8
- Check the issue is not reproducibile

**Comment by mamengoni** [comment]
tested and verified: 

```
config rule 'ns_10'
        option proto 'all'
        option dest 'openvpn'
        option src 'blue'
        option name '10_migrated_openvpn'
        option target 'ACCEPT'
        option log '0'
        option enabled '1'
        list dest_ip '10.0.0.21'
        list src_ip '192.168.11.2'
        list ns_tag 'migrated' 
```

**Comment by gsanchietti** [comment]
Released in nethserver-updates for NethServer 7:
nethserver-firewall-migration-0.0.21-1.ns7.noarch.rpm
