### ISSUE TITLE
Migration: firewall rules with "Any" service migrate incorrectly as empty "Custom Service"

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#727]
**Description:**

During migration from NethSecurity 7.9 to 8, firewall rules that originally used the "Any" service are incorrectly migrated. Instead of retaining "Any" as the destination service, the rules are set to "Custom Service" with no protocol or port specified.

**Steps to Reproduce:**

1. On NethSecurity 7.9, create a firewall rule using the "Any" service.
2. Migrate the configuration to NethSecurity 8.
3. Observe the destination service in the migrated rule.

**Expected Behavior:**  
The migrated firewall rule should retain "Any" as the destination service.

**Actual Behavior:**  
The migrated rule shows "Custom Service" with no protocol or port specified. 

**Example Error:**
```bash
Section ns_80 (80_migrated_openvpn) option 'src' specifies invalid value 'any+'
```

**Additional Information:**

- The concept of "Any" service does not exist in OpenWRT.
- Editing and saving the rule in the UI causes validation errors.

**Comment by gsanchietti** [comment]
**Test case**

- On NethServer 7, install nethserver-firewall-migration-0.0.20-1.2.gcb8325f.ns7.noarch.rpm from testing repository
- Export the archive
- Import the archive inside the NethSecurity 8
- Check the issue is not reproducibile

**Comment by mamengoni** [comment]
Tested and verified.
![image](https://github.com/user-attachments/assets/492191df-7d16-4afa-845b-7806d85ee521)

**Comment by gsanchietti** [comment]
Released in nethserver-updates for NethServer 7:
nethserver-firewall-migration-0.0.21-1.ns7.noarch.rpm
