### ISSUE TITLE
Cannot duplicate a port forward

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#730]
**Description:**

When attempting to duplicate a port forwarding rule on NethSecurity 8, the operation fails, resulting in an error. The issue occurs consistently in virtual machine environments.

**Steps to Reproduce:**

1. Access the port forwarding settings on NethSecurity 8.
2. Select an existing port forwarding rule and click "Duplicate."
3. Observe the error message returned.

**Expected Behavior:**  
The port forwarding rule should be successfully duplicated without errors.

**Actual Behavior:**  
The following error is encountered when attempting to duplicate the rule:
```bash
root@nsec8:~# echo '{"dest_ip":"10.123.123.252","ns_dst":null,"proto":["tcp","udp"],"src_dport":"5000","src_dip":"any","dest_port":"","name":"test pf (Copy)","enabled":"1","log":"0","restrict":[],"ns_src":null,"reflection":"0","reflection_zone":[],"dest":""}' | /usr/libexec/rpcd/ns.redirects call add-redirect
{"error": "redirect_not_added"}
```

**Comment by andre8244** [comment]
**Test case**

Verify the bug is no more reproducible

**Comment by francio87** [comment]
Confirm fixed
