### ISSUE TITLE
Controller: wrong link to unit log page

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#733]
The firewall unit send logs using only the hostname and not the fully qualified domain name.
As an example, a unit named `firewall.test.local` send logs using only `firewall as hostname`.
Such hostnames are listed inside Grafana logs dashboard.

Users can access the the Grafana log dashboard directly from the units page, inside the controller.
But the link contains the fully qualified domain name, instead of only the hostname. As a consquence, the link brings the user to an empty dashboard.

**Steps to Reproduce:**

1. Go to the unit list page in the controller interface.
2. Click the "Open logs" button on a unit with a FQDN like "firewall.test.local"
3. The logs do not appear, as the system is trying to retrieve them with the full name.

**Expected Behavior:**

The system should either use the truncated name in the log retrieval process or handle the full unit name consistently.

**Actual Behavior:**

The unit name is displayed truncated, but logs are requested using the full name, resulting in an error.

**Proposed Solution:**

Make sure rsyslog sends the logs using the FQDN when connected to a remote controller.
Manual configuration:
```bash
echo '$PreserveFQDN on' >> /etc/rsyslog.conf
```

Change current implementation to add the above option when a unit is connected to a controller.
Remove the option when the units is disconnected from a controller.

**Comment by Tbaile** [comment]
After the image update, a manual remove/add unit is needed (or the `echo` mentioned above), if the case is correct that the issue has been verified.
