### ISSUE TITLE
Little bug. UI session expiration

### ISSUE THREAD

**Issue by IZukyWeb** [NethServer/nethsecurity#738]
**Steps to reproduce**

Log into the NS8 UI and wait session expiration

**Expected behavior**

The expired session should close and re-propose login.

**Actual behavior**

The session is not closed and all firewall modules give a red error. 
Logout must be done manually but all errors must be closed first because the popups are above the "logout" button

**Components**

NethSecurity 8 23.05.4-ns.1.2.0
2FA enabled, not tested without 2fa

**Comment by andre8244** [comment]
Hi,

I cannot reproduce the issue, can you please add more details?

> Log into the NS8 UI and wait a few minutes.

The user session expires after 24 hours, I don't understand why you say "a few minutes".

Please click "Copy command" on the error notification and copy here both the command and its output after running it on the shell of the unit.

Browser logs would be useful too: open the developer tools by clicking F12, reproduce your issue and take a screenshot of the errors appearing on the browser console.

**Comment by IZukyWeb** [comment]
You're right, I usually leave the session open on the weekend and I hadn't considered the time that had passed.
I edited the post.
Anyway, if it's 24 hours I think it can be ignored, or would you still prefer me to send the screenshots?
Otherwise, please close the report, thanks

**Comment by andre8244** [comment]
When the session expires you shouldn't get any errors and be redirected to login page. You can try to reproduce your issue in incognito mode, i.e. with all browser extension deactivated. If you need more assistance we'll need all the information requested in my previous comment.

**Comment by gsanchietti** [comment]
Since it's not reproducible, let's close this issue for now, but we can discuss it further on https://community.nethserver.org.

**Comment by IZukyWeb** [comment]
It shows up after 24 hours so it's normal that you haven't been able to reproduce it if 3 hours have passed...
I attach requested screenshots
![Screenshot 2024-09-11 090832](https://github.com/user-attachments/assets/dc251fba-f9a5-4247-80df-7cdcbe961866)
![Screenshot 2024-09-11 090823](https://github.com/user-attachments/assets/62f1f22f-7f1e-4d89-a066-41680d3a9a4a)
![Screenshot 2024-09-11 090739](https://github.com/user-attachments/assets/589de8eb-54ad-4a9d-90d8-46dce18506f4)

**Comment by gsanchietti** [comment]
Thanks for the screenshots, but we are still unable to reproduce.
Maybe is a mix of different causes?
Please open a new threat inside the community form, we will see if we can gather more info from different users.
