### ISSUE TITLE
OpenVPN RW: connection failure after 6 months from activation

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/nethsecurity#739]
All openvpn road-warrior connections stop connecting after 6 months from the server creation.

**Steps to reproduce**

- Set the date one year in the past
- Click on Create server
- Add an account
- Set the real date
- Try to connect

**Expected behavior**

VPN connected

**Actual behavior**

VPN timeout during connection
The firewall log contains:
```
Sep  8 23:58:44 firewall openvpn(ns_roadwarrior1)[4673]: 31.189.39.64:57452 VERIFY ERROR: depth=0, error=CRL has expired: CN=filippo, serial=115157603030633733028860792664376936936
Sep  8 23:58:44 firewall openvpn(ns_roadwarrior1)[4673]: 31.189.39.64:57452 OpenSSL: error:0A000086:SSL routines::certificate verify failed
```

**Workaround**

Regenerate a new CRL:
```
cd /etc/openvpn/ns_roadwarrior1/ && EASYRSA_BATCH=1 EASYRSA_REQ_CN=$(uci get system.@system[0].hostname | cut -d '.' -f 1) /usr/bin/easyrsa gen-crl
```

**Comment by Tbaile** [comment]
## QA:

Reference Image: [23.05.4-ns.1.2.0-32-g3283b557](https://github.com/NethServer/nethsecurity/actions/runs/10795019186/artifacts/1914911648)
Package: https://updates.nethsecurity.nethserver.org/dev/23.05.4/packages/x86_64/nethsecurity/ns-openvpn_0.0.6-1_all.ipk

### Fresh Install
1. Install the reference image linked above
2. Create a OpenVPN RoadWarrior
3. Ensure that the output of
    ```bash
    openssl crl -inform PEM -in /etc/openvpn/ns_roadwarrior1/pki/crl.pem -text -noout
    ```
    confirm that `Next Update` row is in **10 years**

### Image Update
1. Install a stable release of NethSec
2. Create a OpenVPN RoadWarrior
3. Ensure that the output of
    ```bash
    openssl crl -inform PEM -in /etc/openvpn/ns_roadwarrior1/pki/crl.pem -text -noout
    ```
    confirm that `Next Update` row is in **1 year**.
4. Update the image using the reference image linked above
5. Ensure that the output of
    ```bash
    openssl crl -inform PEM -in /etc/openvpn/ns_roadwarrior1/pki/crl.pem -text -noout
    ```
    confirm that `Next Update` row is in **10 years**.

### Package Update
1. Install a stable release of NethSec
2. Create a OpenVPN RoadWarrior
3. Ensure that the output of
    ```bash
    openssl crl -inform PEM -in /etc/openvpn/ns_roadwarrior1/pki/crl.pem -text -noout
    ```
    confirm that `Next Update` row is in **1 year**.
4. Force package update downloading the ipk above 
6. Ensure that the output of
    ```bash
    openssl crl -inform PEM -in /etc/openvpn/ns_roadwarrior1/pki/crl.pem -text -noout
    ```
    confirm that `Next Update` row is in **10 years**.

**Comment by filippocarletti** [comment]
### Fresh install
```
~# openssl crl -inform PEM -in /etc/openvpn/ns_roadwarrior1/pki/crl.pem -text -noout | grep Next
          Next Update: Sep  8 14:35:30 2034 GMT
```

### Image update
```
~# openssl crl -inform PEM -in /etc/openvpn/ns_roadwarrior1/pki/crl.pem -text -noout | grep Next
          Next Update: Mar  9 14:43:25 2025 GMT
~# Connection to 192.168.1.1 closed by remote host.
~# openssl crl -inform PEM -in /etc/openvpn/ns_roadwarrior1/pki/crl.pem -text -noout | grep Next
        Next Update: Sep  8 14:47:03 2034 GMT
```

### Package update
```
~# openssl crl -inform PEM -in /etc/openvpn/ns_roadwarrior1/pki/crl.pem -text -noout | grep Next
        Next Update: Mar  9 15:29:21 2025 GMT
opkg --force-reinstall install /tmp/ns-openvpn_0.0.6-1_all.ipk
~# openssl crl -inform PEM -in /etc/openvpn/ns_roadwarrior1/pki/crl.pem -text -noout | grep Next
        Next Update: Sep  8 15:49:57 2034 GMT
```
