### ISSUE TITLE
DHCP: static leases page size change doesn't work properly

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#740]
**Description:**

When attempting to change the number of displayed Static Leases from 10 to 100, the page does not update as expected. Even though the option is changed, the user is still forced to navigate to page 2 to see all entries.

**Steps to Reproduce:**

1. Go to **DNS and DHCP > Static Leases**.
2. Try to change the display option from 10 to 100.
3. Notice that the list does not adjust, and a second page is still required.

**Expected Behavior:**

When changing the display setting to 100, all static leases should be visible on a single page.

**Actual Behavior:**

The system does not display all static leases on one page, requiring additional navigation.

**Browser Console Error:**

```
TypeError: Cannot set properties of undefined (setting 'value')
    at r.onSelectPageSize.f.<computed>.f.<computed> (DnsDhcpView-5b772a20.js:1:15371)
    at Zr (index-399ee72e.js:13:38)
    ...
```

**Comment by andre8244** [comment]
**Testing image**

[23.05.4-ns.1.2.0-25-g2a6b69cd](https://mattermost.nethesis.it/api/v4/files/1mm7ptuwxfnijnxqewxgyqcgae/preview)

**Test case**

Verify that the bug is no longer reproducible
