### ISSUE TITLE
OpenVPN tunnel client: wrong mode Bridged displayed for an imported tunnel 

### ISSUE THREAD

**Issue by cotosso** [NethServer/nethsecurity#751]
**Steps to reproduce**

- Import an OpenPVN tunnel client configuration generated with another NethSecurity server (it always works in "routed" mode)
- The configuration is flawlessy imported and working in routed mode (tun interface)
- Now edit the configuration via web UI,the displayed **Mode** is Bridged and not Routed 

**Expected behavior**

I expect to see the "advanced setting" displaying the Routed mode

**Actual behavior**

The UI wrongly displays  Bridged mode as selected , now if I press save button I'm going to change the behaviour of the tunnel client (that won't work again).

**Components**
NethSecurity 8 23.05.4-ns.1.2.0-36-gfcc1f065

**Comment by gsanchietti** [comment]
Verified.
