### ISSUE TITLE
OpenVPN tunnel client : wrong "Bridged" mode as new default

### ISSUE THREAD

**Issue by cotosso** [NethServer/nethsecurity#752]
One of last fix changed the OpenVPN tunnel client default from Routed to Bridged.
To avoid problems is better to revert to previous behaviour cause openvpn tunnel client are almost always used in Routed mode and with this new behaviour admins can easily make mistakes.

Another side question is: cause Routed mode is by far the most used it should be presented as first option in the radio button interface (for both OpenVPN tunnel client and OpenVPN roadwarrior panel).

**Steps to reproduce**

- Create an openvpn tunnel client from scratch
- don't even open the "advanced settings"
- press save button and confirm

**Expected behavior**

A new openvpn tunnel client in Routed mode has been created.

**Actual behavior**

A new openvpn tunnel client in Bridged Mode has been created,

**Components**

NethSecurity 8 23.05.4-ns.1.2.0-36-gfcc1f065

**Comment by Tbaile** [comment]
Without releasing a new `ns-ui` package yet (since this issue has been deemed not very critical), please install this ui in a stable firewall to check if the fixes are applied: https://github.com/NethServer/nethsecurity-ui/actions/runs/10825906186/artifacts/1923364440

\cc @cotosso

**Comment by gsanchietti** [comment]
Verified: the tunnel client is created in routed mode:
```
option dev_type 'tun'
option dev 'tuncs1'
```
