### ISSUE TITLE
Historical monitoring

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#754]
Historical monitoring allows the user to see how the firewall is behaving.
Since the firewall does not have enough storage space to retain such data, the statistics are sent to the controller and visible inside Grafana.

**Retention:** 1 month (configurable if possible)

Below are listed the possible dashboards.

**Network Traffic**

**All Networks**
- [x] **Total Daily Traffic** Counter
- [x] **Daily Traffic Chart** Histogram
- [x] **Traffic by Protocol** Table + Graph
- [x] **Traffic by Application** Table + Graph
- [x] **Remote Hosts Traffic** Table + Graph
- [x] **Local Hosts Traffic** Table + Graph

**Single Host**
- [x] **IP Address**
- [x] **Hostname**
- [x] **Total Daily Traffic** Counter
- [x] **Daily Traffic Chart** Histogram
- [x] **Traffic by Protocol** Table + Graph
- [x] **Traffic by Application** Table + Graph
- [x] **Remote Hosts Traffic** Table + Graph

**Connectivity**

- [x] **List of Connectivities** Interface name and device
- [x] **Connectivity Trend** Table or equivalent (Connectivity over time)
- [x] **Current Status & Last 3 Downtime Dates**

**Per Connectivity**
- [x] **Daily Traffic Amount**
- [x] **Graphs (aligned and with same dimensions for correlation):**
  - [x] WAN Traffic Graph
  - [x] Latency Graph to 2 Public Hosts (e.g., 8.8.8.8, 1.1.1.1)
  - [x] Drop Rate Graph to 2 Public Hosts (e.g., 8.8.8.8, 1.1.1.1)

**VPN**

For Each RW Server:
- [x] **Hourly User Connections Histogram**
- [x] **Total VPN-RW Traffic** (Traffic per tunrw section)
- [x] **Top Traffic Users** (Traffic per tunrw section)
- [x] **Total Client Traffic per Hour**
- [x] **Traffic per Client per Hour**

**Security**

- [x] **Total Number of Blocked Packets for the Day**
- [x] **Number of Blocked Packets per Hour**
- [x] **Malware by Direction Pie Chart** (In/Out)
- [x] **Malware by Category Pie Chart**
- [x] **Malware Geomap**
- [x] **Number of Blocked Attacker IPs per Day**
- [x] **List of Most Blocked Attacker IPs**
- [x] **Blocked Attacker IPs per Hour Graph**
- [x] **Attack Geomap**

Other changes:
- [x] send data to the controller only if a subscription is enabled
- [x] add documentation to the administrator manual
- [x] bump controller UI version
- [x] bump controller version
- [x] include latest controller version inside ns8-nethsecurity-controller

See also:
- NethServer/dev#7035

**Comment by gsanchietti** [comment]
**Test case**
- On NS8, install the latest version of the controller: `add-module ghcr.io/nethserver/nethsecurity-controller:latest`m see also the [NS8 related issue](https://github.com/NethServer/dev/issues/7035).
- Configure the controller and make sure to set a valid Max Mind license during the configuration phase
- Install NethSecurity using the image [8-23.05.5-ns.1.2.99-alpha1-29-gadbb0fcc56](https://updates.nethsecurity.nethserver.org/dev/8-23.05.5-ns.1.2.99-alpha1-29-gadbb0fcc56/targets/x86/64/nethsecurity-8-23.05.5-ns.1.2.99-alpha1-29-gadbb0fcc56-x86-64-generic-squashfs-combined-efi.img.gz) or newer
- On the NethSecurity, execute this command to circumvent the version controller awareness: `version=2.0.0; sed -i '/^Package: ns-api$/,/^Version:/ s/^Version: .*/Version: '"$version"'/' /usr/lib/opkg/status`
- Connect the NethSecurity to the controller using the "Controller" page
- Wait at least 15 minutes for the unit to send data to the controller
- Access Grafana inside the controller, verify that all dashboards are working correctly

**Comment by Tbaile** [comment]
Everything works fine, if the blessing from `dpireport` comes around
