### ISSUE TITLE
OpenVPN Tunnel Client resets cipher to `AES-128-CBC` 

### ISSUE THREAD

**Issue by Tbaile** [NethServer/nethsecurity#758]
**Steps to reproduce**

1. Configure or import a OpenVPN Tunnel Client
2. Edit the cipher for the tunnel 

**Expected behavior**

Client is configured correctly with the Cipher 

**Actual behavior**

Cipher is always being reset to `AES-128-CBC`

**Components**

ns-api `1.0.1`

**See also**

Internal discussion: https://mattermost.nethesis.it/nethesis/pl/4md736f1hjnq8ng51pd65xc1qr

---

PRs:
 - https://github.com/NethServer/nethsecurity/pull/759

**Comment by mamengoni** [comment]
Tested and verified!

![image](https://github.com/user-attachments/assets/a393e4e1-d79e-411f-a63d-604b7c27cacf)
