### ISSUE TITLE
NethServer API server fails to reload valid paths

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#764]
**Steps to reproduce**

- Add new APIs to the NethSecurity API server.
- Attempt to reload the NethSecurity API server.
- Check the logs for the expected reload message.

**Expected behavior**

- Upon reloading, the API server should log a line indicating the reloading of the valid path list, such as:
  ```
  Sep 19 08:22:56 NethSec nethsecurity-api[12819]: nethsecurity_api 2024/09/19 08:22:56 main.go:63: Reloading valid path list
  ```

**Actual behavior**

- The NethSecurity API server does not reload the valid paths.
- If new APIs have been added, the user is unable to use them.
- The server does not log the expected reload message.

**Components**

NethSecurity Image: 8-23.05.4-ns.1.2.0

**Comment by gsanchietti** [comment]
Testing image: https://github.com/NethServer/nethsecurity/actions/runs/10938089763/artifacts/1952191718

**Comment by Tbaile** [comment]
`ns-api-server` restarts correctly.
