### ISSUE TITLE
Migration: missing account_email in ACME

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#773]
**Steps to reproduce**

- Perform a migration from NethServer 7 to the current version.
- Check the ACME configuration after the migration.

**Expected behavior**

- The `acme.@acme[0].account_email` property should be correctly populated with the appropriate email address, such as `no-reply@nethsecurity.org`.

**Actual behavior**

- After migration, the `account_email` option is missing in the ACME configuration, causing the following error:
  ```
  Sep 23 00:00:00 sole crond[12701]: USER root pid 18426 cmd /etc/init.d/acme start
  Sep 23 00:00:00 sole acme: account_email option is required
  ```

- Checking the ACME configuration shows that the `account_email` field is absent:
  ```
  root@sole:~# uci show acme
  acme.@acme[0]=acme
  acme.@acme[0].debug='0'
  acme.example_subdomain=cert
  acme.example_subdomain.enabled='0'
  acme.example_subdomain.staging='1'
  acme.example_subdomain.domains='example.net' 'www.example.net' 'mail.example.net'
  acme.example_subdomain.validation_method='webroot'
  acme.ns_default=cert
  acme.ns_default.enabled='1'
  acme.ns_default.domains='fw.mydomain.com'
  acme.ns_default.key_type='rsa2048'
  acme.ns_default.validation_method='standalone'
  ```

- The missing property that causes the issue is:
  ```
  acme.@acme[0].account_email='no-reply@nethsecurity.org'
  ```

**Components**

NethSecurity Image: 8-23.05.4-ns.1.2.0

**Comment by gsanchietti** [comment]
**Test case**

Follow these instructions to try the fix without a real machine where all Let's Encrypt requirements are satisfied:
- access the machine with SSH and go to `/root`
- execute:
  ```
  mkdir /root/export
  cat > /root/export/acme.json <<EOF
  {
    "config": {
      "domains": [
        "le.gs.nethserver.net"
      ],
      "account_email": ""
    }
  }
  EOF
  ```
- import: `/usr/share/ns-migration/80acme /root/export && uci commit`
- execute: `uci get acme.@acme[0].account_email`, it should return `no-reply@nethsecurity.org`

**Comment by Tbaile** [comment]
Verified.
