### ISSUE TITLE
Impossible to set a default certificate for reverse proxy

### ISSUE THREAD

**Issue by Tbaile** [NethServer/nethsecurity#776]
**Steps to reproduce**

- Upload a custom certificate
- Attempt to set the new certificate as default

**Expected behavior**

- Command is successful and list of changes pops up

**Actual behavior**

- Error returns that `re` is a reference missing 

**Components**

ns-api <~ `0.0.87`
regression introduced by 139dbfaf957ef0df383d174d5aa1d5cd140ea2eb

**See also**

Internal discussion: https://mattermost.nethesis.it/nethesis/pl/axmxh7rxpffjmf5rz4zm59tpcc

----

PR: 
- #777

**Comment by gsanchietti** [comment]
Verified with a LE certificate.
