### ISSUE TITLE
Migration: wrong zone for OpenVPN and IPSec custom rules

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#788]
**Steps to reproduce**

- On NethServer 7, create:
   -  an host object named `s1` containing an IP of the OpenVPN roadwarrior server
   -  an host object named `s2` containing an IP of a remote network from an OpenVPN tunnel
   -  an host object named 's3' containing an IP of a remote network from an IPsec tunnel
   - an host object named `d4` containing an IP of the LAN
- Create a rule for each source host (`s1`, `s2` and `s3`) to the destination host d4
- Perform a migration to NethSecurity
- Review firewall rules related to IPsec and OpenVPN connections in `/etc/config/firewall`.

**Expected behavior**

- Firewall rules involving IPsec tunnels should correctly use `ipsec` instead of `ipsectun`.
- Rules for OpenVPN roadwarrior (rw) should use `rwopenvpn` instead of `openvpn`. Alternatively, setting the zone to `any` could simplify the rule configuration, avoiding duplication of both source and destination.

**Actual behavior**

- Post-migration, firewall rules still use the old configurations (`ipsectun` for IPsec tunnels and `openvpn` for roadwarrior connections), which leads to incorrect behavior.

**Required changes (diff):**

```diff
--- firewall    2024-09-23 15:33:26.000000000 +0000
+++ /etc/config/firewall        2024-09-23 15:42:53.899041348 +0000
@@ -227,14 +227,14 @@
##src cambiata da openvpn a rwopenvpn se si tratta di una roadwarrior
 config rule 'ns_1'
        option proto 'all'
        option dest 'guest'
-       option src 'openvpn'
+       option src 'rwopenvpn'
        option name '1_migrated_openvpn'
        option target 'ACCEPT'
        list ns_tag 'migrated'

 config rule 'ns_2'
@@ -251,29 +251,29 @@
        list ns_tag 'migrated'

# su src e dest ipsectun cambiato in ipsec
 config rule 'ns_3'
        option dest 'lan'
-       option src 'ipsectun'
+       option src 'ipsec'
        option name '3_migrated'
        option target 'ACCEPT'
        option ns_service '*'
```

**Components**

NethSecurity Image: 8-23.05.4-ns.1.2.0

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-firewall-migration-1.0.0-1.4.g651d7cd.ns7.noarch.rpm


**Test case**
- Check the issue is not reproducible
- Please not that:
  - `rwopenvpn` zone is added only the OpenVPN Road Warrior server was enabled on NS7 
  - `openvpn` zone is add only if there was at least une OpenVPN tunnel enabled on NS7
  - `ipsec` zone is add only if there was at least une IPsec tunnel enabled on NS7

**Comment by cotosso** [comment]
the issue is not reproducible, in firewall rules openvpn zone is set to *Any* (rule ns_3)  while ipsec zone is preserved (rule ns_4):
```
config rule 'ns_3'
        list dest_ip '10.66.66.66'
        option proto 'all'
        option dest 'guest'
        option src '*'
        option name '3_migrated'
        list src_ip '10.88.88.88'
        option target 'ACCEPT'
        list ns_tag 'migrated'
        option ns_service '*'
        option log '0'
        option enabled '1'

config rule 'ns_4'
        list dest_ip '10.66.66.66'
        option proto 'all'
        option dest 'guest'
        option src 'ipsec'
        option name '4_migrated'
        list src_ip '10.22.22.22'
        option target 'ACCEPT'
        list ns_tag 'migrated'
        option ns_service '*'
        option log '0'
        option enabled '1'
```
