### ISSUE TITLE
Migration: FlashStart not enabled on guest/blue interface

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#792]
**Steps to reproduce**

- Enable FlashStart filter on NethServer 7 both for blue and green interfaces
- Perform a migration from NethServer 7 to NethSecurity.

**Expected behavior**

- FlashStart should be enabled on both the lan and guest interfaces after the migration, matching the configuration from NethServer 7.

**Actual behavior**

- FlashStart is only enabled on the lan interface.
- The blue interface (guest zone) is not configured with FlashStart, even though it was enabled before migration.

**Workaround**

- After migration, manually enable FlashStart on the guest zone.

**Components**

NethSecurity Image: 8-23.05.4-ns.1.2.0

**See also**

https://community.nethserver.org/t/my-experience-migrating-from-nethsecurity-7-to-8/24518

---

Thanks to **izuky**

**Comment by cotosso** [comment]
nethserver-firewall-migration now creates the right json file:

```
root@NSec8-VM-davidem:~# cat /root/export/flashstart.json | jq
{
  "config": {
    "password": "mypassword",
    "bypass": [],
    "user": "myuser",
    "zones": [
      "lan",
      "guest"
    ],
    "enabled": "1"
  }
}
```
