### ISSUE TITLE
Interface page fails due to invalid JSON with QoS enabled on PPPoE interface

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#804]
**Steps to reproduce**

1. Create a PPPoE WAN interface named `WAN1_WiMe`.
2. Enable QoS on the `WAN1_WiMe` interface.
3. On a NethSecurity system, attempt to access the interface page from the GUI.
4. The system fails to load with an error, and logs show the following:

   ```bash
   root@firewall:~# /usr/libexec/rpcd/ns.devices call list-devices
   {"error": "json_given_is_invalid"}
   ```

5. Running the following command reveals the issue with the `ip -j address` command:

   ```bash
   root@firewall:~# ip -j address | jq
   parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 1, column 3929
   ```

**Expected behavior**

- The interface list should load properly without errors.

**Actual behavior**

- The error is traced to invalid characters in the output of the `ip -j address` command, which causes the JSON to fail.

**Investigation**

- The issue is related to a bad character or string in one of the interfaces created by `qosify`. Specifically, the interface `ifb-pp<bad_char>` causes issues with both the `ifconfig` and the JSON output of the `ip` command.

- If the `qosify` service is stopped, the issue goes away:

   ```bash
   /etc/init.d/qosify stop
   ```

**Workaround**

- A temporary fix involves renaming the interface, particularly for `pppoe` interfaces, to shorter names (max 5 characters, avoiding special characters) to prevent this issue. For Ethernet interfaces, the name length limit is 13 characters.

- This issue likely appeared after enabling `qosify`.

**Additional context**

- If the partner cannot rename the `pppoe` interface due to system access limitations, the issue might persist until this can be done.

**Components**

NethSecurity Image: 8-23.05.4-ns.1.2.0

**Comment by andre8244** [comment]
**Testing image**

[23.05.5-ns.1.2.99-alpha1-49-gd35f90fee2](https://github.com/NethServer/nethsecurity/actions/runs/11163745047/artifacts/2011279154)

**Test case 1**
- Go to **Network > Interfaces and devices**
- Click **Configure** on an unassigned device
- Enter an interface name longer than 5 characters
- Select WAN zone and PPPoE protocol
- Click **Configure interface**
- Verify that a validation error is shown under **Interface name** field
- Enter an interface name containing at maximum 5 characters
- Click **Configure interface**
- Go to **Network > QoS**
- Configure Quality of Service on the previously configured interface
- Verify that QoS work as expected

**Test case 2**
- Go to **Network > Interfaces and devices**
- Click **Configure** on an unassigned device
- Enter an interface name longer than 5 characters
- Configure the device by selecting a protocol **different** from PPPoE
- Click **Configure interface**
- Reopen the configuration drawer by clicking **Edit** on the previously configured interface
- Select WAN zone and PPPoE protocol
- Click **Configure interface**
- Verify that a validation error is shown under **Interface name** field. It should invite the user to reconfigure the device from scratch
