### ISSUE TITLE
Migration: root password authentication flag incorrectly displayed inside the UI

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#806]
**Steps to reproduce**

1. On the NethServer 7 instance, ensure that "Allow root access / with password" is enabled via Cockpit.
2. Perform an in-place migration from NethServer 7 to NethSecurity (this is reproducible also with a migration with export file)
3. Complete the migration and reboot the machine.
4. After the system comes back online, access the NethSecurity UI and navigate to **Remote Access** settings. Observe that the checkbox for "Allow root access with password" is not selected, even though root access with a password still functions as expected.

**Expected behavior**

- After migration, the checkbox in the **Remote Access** section of the NethSecurity UI for "Allow root access with password" should remain checked, reflecting the correct configuration as it was before the migration.

**Actual behavior**

- In the **Remote Access** section of the NethSecurity UI, the checkbox for "Allow root access with password" is unchecked, though root password authentication continues to work.
- Reviewing the UCI configuration shows:

   ```bash
   uci show dropbear
   dropbear.@dropbear[0]=dropbear
   dropbear.@dropbear[0].PasswordAuth='1'
   dropbear.@dropbear[0].RootPasswordAuth='1'
   dropbear.@dropbear[0].Port='22'
   ```

- The flag for root password authentication is set to '1' instead of 'on'. According to the [official OpenWRT documentation](https://openwrt.org/docs/guide-user/base-system/dropbear#dropbear), valid values are '0' and '1', but the NethSecurity UI and LuCI expect 'on'/'off' to correctly display the checkbox status.

**Workaround**

- Although the checkbox in the **Remote Access** UI does not reflect the correct status, root password authentication works correctly since the UCI configuration is valid. You can log in via SSH as root using the password.

**Components**

NethSecurity Image: 8-23.05.4-ns.1.2.0

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-firewall-migration-1.0.1-1.1.g58792b3.ns7.noarch.rpm

**Test case**
- Check the issue is not reproducible

**Comment by francio87** [comment]
Confirm, fixed ✅ 

```bash
[root@ns79 ~]# rpm -q nethserver-firewall-migration
nethserver-firewall-migration-1.0.1-1.1.g58792b3.ns7.noarch
```

```bash
[root@ns79 ~]# config show sshd
sshd=service
    AllowEveryone=none
    AllowGroups=
    AllowLocalGroups=wheel
    LoginGraceTime=2m
    MaxAuthTries=6
    PasswordAuthentication=yes
    PermitRootLogin=yes
    Protocol=2
    StrongEncryption=enabled
    SubsystemSftp=yes
    TCPPort=60123
    UsePAM=yes
    access=green,red
    status=enabled
```

```bash
root@ns79:~# uci show dropbear
dropbear.@dropbear[0]=dropbear
dropbear.@dropbear[0].PasswordAuth='on'
dropbear.@dropbear[0].RootPasswordAuth='on'
dropbear.@dropbear[0].Port='60123'
dropbear.@dropbear[0].GatewayPorts='1'
dropbear.@dropbear[0].RootLogin='1'
dropbear.@dropbear[0].MaxAuthTries='6'
```


![immagine](https://github.com/user-attachments/assets/68eb20c8-d047-4c05-a07c-f4aaf2e16c17)
