### ISSUE TITLE
Zones and Policies page incorrectly displays the Logging status for each zone

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#807]
**Steps to reproduce:**

1. Access NethSecurity's **Zones and policies** page.
2. Observe the **Logging** field for each zone.
   - Logging is shown as **disabled** if the zone does not have the `log` option.
   - Logging is shown as **enabled** if the zone has the `log` option, even if set to `0`.
3. To replicate from the command line:
   ```bash
   uci set firewall.ns_wan.log=0
   uci commit firewall
   /etc/init.d/firewall reload
   ```

**Expected behavior:**

- The **Logging** field in the **Zones and policies** page should accurately reflect the logging status based on the zone's configuration. 

**Actual behavior:**

- The logging field displays **enabled** even when the `log` option is set to `0`.

**Tasks to fix:**

1. Ensure the zone list correctly shows the logging status.
2. Add functionality to enable or disable logging from the UI.
3. Document the logging functionality for zones:
   - When logging is enabled, all dropped or rejected packets destined for that zone are automatically logged, even if the log flag in the rule is turned off.

**Components:**

NethSecurity Image: 8-23.05.4-ns.1.2.0

**Comment by francio87** [comment]
Not Verified ❌ 

The UI show Logging `ON` even if the option `log` of the zone is set to `0` :

```bash
root@NethSec-test:~# uci show firewall.ns_lan
firewall.ns_lan=zone
firewall.ns_lan.name='lan'
firewall.ns_lan.network='lan'
firewall.ns_lan.input='ACCEPT'
firewall.ns_lan.output='ACCEPT'
firewall.ns_lan.forward='ACCEPT'
root@NethSec-test:~# 
root@NethSec-test:~# 
root@NethSec-test:~# 
root@NethSec-test:~# uci show firewall.ns_guest.log
firewall.ns_guest.log='0'
```

![image](https://github.com/user-attachments/assets/163ae06a-8547-4aaa-b610-8c62281e82ab)

New Zones are created with the option `log='0'` :

```bash
root@NethSec-test:~# uci changes
firewall.ns_new='zone'
firewall.ns_new.name='new'
firewall.ns_new.input='DROP'
firewall.ns_new.forward='DROP'
firewall.ns_new.output='ACCEPT'
firewall.ns_new.log='0'
firewall.ns_new='7'
```


but the UI only show `OFF` if the option is missing

**Comment by gsanchietti** [comment]
Test image: https://github.com/NethServer/nethsecurity/actions/runs/11219684738/artifacts/2025013322

**Comment by francio87** [comment]
Verified ✅
