### ISSUE TITLE
Missing parameters in QoS configuration

### ISSUE THREAD

**Issue by cotosso** [NethServer/nethsecurity#808]
**Steps to reproduce**

- Create a wan interface with a name other that "wan" (e.g., "FIBER1000")
- Enable QoS on that interface
- Check the QoS parameters configuration on the interface.

**Expected behavior**

QoS parameters such as `overhead_type`, `ingress`, `egress`, `mode`, `nat`, `host_isolate`, and `autorate_ingress` should be present and properly set for any interface, regardless of the name assigned (e.g., "wan" or "FIBER1000").

**Actual behavior**

QoS parameters (such as `overhead_type`, `ingress`, `egress`, `mode`, `nat`, `host_isolate`, and `autorate_ingress`) are only applied if the interface is named "wan". For interfaces with different names (e.g., "FIBER1000"), these parameters are missing. Below is an example of the configuration:

```bash
config interface 'wan'
       option name 'wan'
       option disabled '1'
       option bandwidth_up '100mbit'
       option bandwidth_down '100mbit'
       option overhead_type 'none'
       option ingress '1'
       option egress '1'
       option mode 'diffserv4'
       option nat '1'
       option host_isolate '1'
       option autorate_ingress '0'

config interface 'FIBER1000'
       option name 'FIBER1000'
       option disabled '0'
       option bandwidth_up '1000mbit'
       option bandwidth_down '1000mbit'
```

The following QoS parameters, present in the "wan" interface, are missing in the "FIBER1000" interface:

```bash
       option overhead_type 'none'
       option ingress '1'
       option egress '1'
       option mode 'diffserv4'
       option nat '1'
       option host_isolate '1'
       option autorate_ingress '0'
```

Due to the missing parameters the QoS service will limit the available bandwidth

**Components**

NethSecurity 8-23.05.4-ns.1.2.0

**Comment by gsanchietti** [comment]
Reported options are not valid for all interfaces, also some option seems not existing inside the qosify code.
Waiting for a better analysis before implementing any change.

**Comment by gsanchietti** [comment]
Please note that the above are the defaults (taken from config file):
```
	option ingress 1
	option egress 1
	option mode diffserv4
	option nat 1
	option host_isolate 1
	option autorate_ingress 0
	option ingress_options ""
	option egress_options ""
	option options ""
```

The only option that can make sense is `overhead_type`.
Valid values (taken from the init.d) are:
```
                conservative
                pppoa-vcmux
                pppoa-llc
                pppoe-vcmux
                pppoe-llcsnap
                bridged-vcmux
                bridged-llcsnap
                ipoa-vcmux
                ipoa-llcsnap
                pppoe-ptm
                bridged-ptm
                docsis
                ethernet
```

**Comment by gsanchietti** [comment]
The issue regarding QoS performance has been discussed and several key points were identified:
    - Upload bandwidth is managed correctly, but download bandwidth is heavily influenced by the CPU capacity.
    - Low-power devices (e.g., Z1+) struggle with high bandwidths (e.g., 2.5Gbps), limiting performance.
    - The presence of netifyd and the default enabled split-gso option further degrade performance.
    - Recommendations include disabling split-gso for very high bandwidths (above 10Gbps) and setting ingress to 0 for low-end devices with bandwidths above 1.2Gbps.
    - The default nat option should be used only for WAN, with nonat for local networks.
    - Proposed solutions include adding a checkbox in the UI to:
       - enable/disable QoS management for download and upload
       - disable split-gso disabling
       - automating nat/nonat management based on the role
    - The current bug will be closed and a new feature request will be created to track these enhancements.
