### ISSUE TITLE
Updating `ns-api` doesn't reload `ns-api-server`

### ISSUE THREAD

**Issue by Tbaile** [NethServer/nethsecurity#810]
nethsecurity-api-server has a security measure that allows executing all files in /usr/libexec/rpcd/ only if the files are contained within a package. This prevents the possibility of executing an arbitrary file if, for some reason, it was loaded there.

To implement this security measure, nethsecurity-api-server keeps a list of allowed files. This list is updated with a /etc/init.d/ns-api-server reload.

The reload is invoked with every ns-api update.

Reload support was introduced in version 1.0.0 of nethsecurity-api-server, which was updated on the machines on September 25th.

Today, ns-api was updated, which triggered the reload, but the reload never worked because an older version of nethsecurity-api-server, which does not handle reload, is still running on the machines.

In practice, the September 25th update did not correctly restart nethsecurity-api-server, hence the bug (I have no idea why, procd doesn't log anything).

To verify this:

Execute the reload /etc/init.d/ns-api-server reload: you won’t see anything in the messages. Restart the daemon with /etc/init.d/ns-api-server restart, and now you’ll see something in the log like Oct 1 15:53:52 fw nethsecurity-api[30548]: nethsecurity_api 2024/10/01 15:53:52 main.go:63: Reloading valid path list.

The correct workaround is to restart the API server. It seems that all firewalls are affected.

**Components**

- NethSecurity 8 - 23.05.4

**See also**

- [Internal discussion](https://mattermost.nethesis.it/nethesis/pl/mp683ojb53yx3m9hoep4pih3sa)

**Comment by gsanchietti** [comment]
Verified and released for 23.05.4:
- ns-api-server 1.1.0-1
- ns-api 1.0.3-2
