### ISSUE TITLE
Support virtual machine tools as packages

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#816]
Currently the NethSecurity image ships qemu tools directly inside the image.
Users have requested access also to VMWare tools.

**Proposed solution**

Remove all tools from the image and provide them as optional packages

Involved packages:
- qemu-ga 
- open-vm-tools

Benefits of this solution:
- the image will be smaller
- kernel modules and special daemon will be loaded only when required

Please note that optional packages will not be preserved across image upgrades.
System administrator will have to reinstall them, if needed.

**Comment by gsanchietti** [comment]
**Test case 1: qemu**
- On a machine running inside QEMU, install the package:
  ```
  opkg update &&  opkg install qemu-ga
  ```
- Start the daemon: `/etc/init.d/qemu-ga start`
- Verify the daemon is running: `ps aux | grep qemu-ga`

**Test case 2: vmware*
- On ma chine running inside VMWare, install the package:
  ```
  opkg update &&  opkg install open-vm-tools
  ```
- Start the daemon: `/etc/init.d/vmtoolsd start`

**Comment by Tbaile** [comment]
Both packages install, however they only work after a reboot (which is kinda understandable due to the nature of the packages)

If this is acceptable, the issue is verified.
