### ISSUE TITLE
Port forward: support all objects inside restrict field

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#818]
**Description**:  
- Implement support for multiple object types in the "Restrict access from" field on the Port Forward page.
- The documentation states that `ns_src` is mapped to an `ipset` and can be any type of object to limit access to a port forward.
- Verify manually which object types work within the field and report back.

**Additional Notes**:  
- Openwrt allows to limit a port forwarding rule to a single source ip/network/range  or to a specific ipset.
  An ipset can use multiple IPs and networks as src_ip o src_net, but it **can't** use ip ranges
- This seems to be a limitation of the API rather than the UI.

**Action Items**:
1. [x] Update the API to return all supported objects inside the `list-object-suggestions` function; exclude host sets with subtype `range`
2. [x] Update the UI to handle the new object types (avoid to add an extra `objects/` prefix when selecting an object)
3. [x] Update the UI to correctly display the content of objects inside the tooltip
4. [x] Update the UI by adding an `i` near `Destination object` label: the tooltip must states that all objects are supported except for host sets containing IP ranges
5. [x] Update the developer documentation
6. [x] Update the administrator manual

References:
- https://mattermost.nethesis.it/nethesis/pl/kc65krpqj7f1xfph35azkdutbo (private chat)
- https://community.nethserver.org/t/bug-nethsecurity-port-forwarding/24623

**Comment by gsanchietti** [comment]
This is the tooltip glitch for objects:
![Screenshot from 2024-10-03 10-22-14](https://github.com/user-attachments/assets/783e7242-4689-403a-94de-26a54d3bd05c)

**Comment by andre8244** [comment]
**Testing image**

[23.05.5-ns.1.2.99-alpha1-56-gd8e4a81a1b](https://github.com/NethServer/nethsecurity/actions/runs/11183072021/artifacts/2016638026)

**Test case**
- Create various objects
  - Go to **Network > DNS and DHCP > Static leases** and create at least one reservation
  - Go to **Network > DNS and DHCP > DNS records** and create at least one DNS record
  - Go to **Users and objects > Objects > Host sets** and create various objects, using DHCP reservation, DNS records, IP ranges, other host sets and IP addresses as records
  - Go to **Users and objects > Objects > Domain sets** and create at least one domain set
- Go to **Firewall > Port forward**
- Click **Add port forward**, expand **Advanced settings**, choose **Select an object** as **Restrict access from** and open **Restricted object** combobox
- Verify that all objects are listed, except host sets containing IP ranges
- Create more port forwards using different restricted objects
- For every port forward created:
  - Verify that the object displayed under the table column **Restricted access from** is correct
  - Click the object under **Restricted access from** and verify that the records displayed in the tooltip are correct

**Comment by cotosso** [comment]
In the port forward section (advanced) :
* All objects are listed except ip ranges
* tooltips are corrects
* created rules in fw4 are consinstent 



```
        chain dstnat_wan {
                tcp dport 777 ip saddr @ns_591d35dc_ipset counter packets 0 bytes 0 dnat ip to 192.168.56.88:777 comment "!fw4: rule1"
                tcp dport 888 ip saddr @ds1 counter packets 0 bytes 0 dnat ip to 192.168.56.88:888 comment "!fw4: rule2"
                tcp dport 333 ip saddr @ns_0caeb8cb_ipset counter packets 0 bytes 0 dnat ip to 192.168.56.88:333 comment "!fw4: rule3"
                tcp dport 444 ip saddr @ns_dbc6f098_ipset counter packets 0 bytes 0 dnat ip to 192.168.56.88:444 comment "!fw4: rule4"
        }
```


```
        set ds1 {
                type ipv4_addr
                timeout 11m
                elements = { 35.214.216.68 expires 6m13s390ms, 104.16.81.40 expires 6m59s770ms,
                             104.16.82.40 expires 6m59s770ms }
        }

        set ns_591d35dc_ipset {
                type ipv4_addr
                flags interval
                auto-merge
                elements = { 22.22.22.22, 33.33.33.33,
                             44.44.44.44 }
        }

        set ns_0caeb8cb_ipset {
                type ipv4_addr
                flags interval
                auto-merge
                elements = { 192.168.56.67, 192.168.56.99 }
        }

        set ns_dbc6f098_ipset {
                type ipv4_addr
                flags interval
                auto-merge
                elements = { 22.22.22.22, 33.33.33.33,
                             44.44.44.44, 192.168.56.55 }

```

**Corner case**

If I declare a host set with inside another host set which is an iprange it is displayed and selectable in the list.
![image](https://github.com/user-attachments/assets/cde7445f-3dee-4b5d-a838-9073b2b0a703)

The rule will be displayed in the UI but it **won't be created**

**Comment by cotosso** [comment]
Administrator manual PR: https://github.com/NethServer/nethsecurity-docs/pull/126

**Comment by cotosso** [comment]
just tested the new image (alpha1-65) and the corner case is not present anymore
