### ISSUE TITLE
MultiWAN: UI does not provide feedback when creating a rule with a name longer than 12 characters

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#835]
**Issue description:**

When creating a MultiWAN rule with a name longer than 12 characters, the UI does not provide any feedback, and the rule is not created. The user is left unaware of the issue, as no error message or indication is displayed.

**Steps to reproduce:**
1. Navigate to the **MultiWAN** page.
2. Click on the **Create rule** button.
3. Create a rule with a name longer than 12 characters.
4. Observe that the rule is not created, and no feedback is provided by the UI.

**Current behavior:**
- The UI fails to create the rule and does not display any error or feedback to the user.

**Expected behavior:**
- The UI should validate the rule name length and display an error message if the name exceeds the 12-character limit, preventing the creation of the rule.

**Proposed solution:**
- Implement proper validation of the rule name length in the UI and ensure that an error message is displayed when the name exceeds 12 characters.

**Components:**
NethSecurity Image: 8-23.05.4-ns.1.2.0

**Comment by andre8244** [comment]
**Testing image**
[23.05.5-ns.1.3.0-3-g1126be845b](https://github.com/NethServer/nethsecurity/actions/runs/11387276317/artifacts/2069443035)

**Test case**
Verify that the bug can no longer be reproduced

**Comment by gsanchietti** [comment]
Verified: the validator is enforced both for policies and rules
