### ISSUE TITLE
PPPoE connection does not re-establish after disconnection with keepalive option enabled

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#843]
**Issue description:**

When a PPPoE connection drops, it fails to re-establish automatically if the `keepalive` option is enabled. To restore the connection, the `keepalive` option must be removed manually, which affects the reliability of the connection. Additionally, the `keepalive` option as currently configured disables the detection of down states, keeping the connection up even though no traffic is being passed.

**Steps to reproduce:**
1. Set up a PPPoE WAN connection with the `keepalive` option enabled.
2. Ensure that the connection is interrupted (for instance, by disconnecting the line or simulating a network drop).
3. Observe that the connection does not re-establish automatically.

**Current behavior:**
- The PPPoE connection does not reconnect after a disconnection when the `keepalive` option is set. Moreover, the `keepalive` option prevents the system from detecting that the connection is down, leaving it technically "up" while no traffic passes through.

**Expected behavior:**
- The PPPoE connection should automatically reconnect even if the `keepalive` option is enabled.
- The system should correctly detect when the connection is down and restore it.

**Proposed solution:**
- Revert PR [#292](https://github.com/NethServer/nethsecurity/pull/292) so that the `keepalive` option is no longer set during configuration.
- During updates, ensure that the `keepalive` option is removed from existing PPPoE connections to prevent future connection issues.

**Workaround**

Given the interface name is `fc1`:
```
uci delete network.fc1.keepalive
uci commit network
ifdown fc1
ifup fc1
```

**Components:**
NethSecurity Image: 8-23.05.4-ns.1.2.0

**Comment by gsanchietti** [comment]
Testing image: https://github.com/NethServer/nethsecurity/actions/runs/11401451606/artifacts/2073457839

**Test case 1**
- Configure a PPPoE interface on a clean NethSecurity 1.3.0
- Change the repositories from stable to dev
- Update the ns-api package using the force option
- Verify the keepalive option has been removed

**Test case 2**
- Configure a PPPoE interface on a clean NethSecurity 1.3.0
- Update the machine with above image
- Verify the keepalive option has been removed

**Test case 3**
- Install a clean machine with image above
- Create a new PPPoE interface
- Verify the keepalive option is not present

**Comment by Tbaile** [comment]
- [X] Case 1
- [X] Case 2
- [X] Case 3

Note: the cases were verified with the image 1.3.0-15, not with the 1.3.0-11 as the QA provided, 1.3.0-11 seems not to include such fixes.
