### ISSUE TITLE
DHCP Static Lease: Incorrect MAC Address Format Handling

### ISSUE THREAD

**Issue by cotosso** [NethServer/nethsecurity#847]
**Steps to reproduce**

- Navigate to the DHCP static lease configuration in the UI.
- Add a static lease with a MAC address using the dash-separated format (e.g., `ac-30-de-67-3f-99`).
- Save the configuration.

**Expected behavior**

The system should accept both colon-separated (`ac:30:de:67:3f:99`) and dash-separated (`ac-30-de-67-3f-99`) MAC address formats in the UI and correctly assign IP addresses based on the static lease.

**Actual behavior**

The dash-separated MAC address format is accepted by the UI but is not handled correctly by the DHCP server, leading to failed IP address assignment.

**Components**

NethSecurity Image: 8-23.05.4-ns.1.2.0

**Comment by andre8244** [comment]
**Testing image**

[23.05.5-ns.1.3.0-11-g54ebc4f2b0](https://github.com/NethServer/nethsecurity/actions/runs/11401451606/artifacts/2073457839)

**Test case**

Verify that the bug is no longer reproducible

**Comment by gsanchietti** [comment]
Verified: the UI accepts both format but always save the one with `:` inside the UCI config
