### ISSUE TITLE
MultiWAN: set last_resort field

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#853]
It was identified that the `ns_default` policy in mwan3 does not default to "default" when the uplink is down. This behavior deviates from the intended configuration during the development phase, where the "default" value was expected for such scenarios. The author of mwan3 also recommends setting `last_resort` to "default." Recent testing has confirmed the need for this option.

**Proposed solution**

The option `uci set mwan3.ns_default.last_resort='default'` should be applied to ensure that the `last_resort` value defaults to "default" when all WAN connections fail. Additionally, it is necessary to apply the fix through a `uci-defaults` script to ensure it is implemented in existing installations. Without this, the fix will only apply during migration updates.

**Alternative solutions**

An alternative would be to maintain the current configuration, where the `last_resort` value remains set to 'unreachable'. However, this would risk no fallback mechanism if all WANs go down, preventing the automatic restoration of the connection.

**Additional context**

The issue emerged during testing, where it was observed that the `last_resort` policy had not been properly configured. The last_resort options is already set during [migration](https://github.com/NethServer/nethsecurity/commit/c8bc8237e1666dbde5bd52e03a27c7b61d77e73f).

**Comment by Tbaile** [comment]
Image: TBA

QA:
1. Image update
  1.1 Install a stable version with 2 REDs
  1.2 Add 2 MWANs (you can use the "custom" type to add a single RED per policy)
  1.3 Update the unit with the image provided above
  1.4 Check through shell that `uci show mwan3 | grep last_resort` shows both MWANs and they're both set to "default"
2. Add a new MWAN
  2.1 Install the image provided above
  2.2 Add a new MWAN
  2.3 Ensure that in the "changes" section `last_resort` is set to default

**Comment by cotosso** [comment]
Test Case 1 verified:
```
root@NSec8-VM-davidem:~# uci show mwan3 | grep last_resort
mwan3.ns_default.last_resort='default'
```
