### ISSUE TITLE
Migrating DHCP duplicates entries due to name mismatch

### ISSUE THREAD

**Issue by Tbaile** [NethServer/nethsecurity#855]
When migrating from NS7, a DHCP field is being set with a incorrect naming scheme from the one used by NethSecurity.
This causes a issue where:
- you'll have a configuration that doesn't match the standard used by NethSecurity (named `dhcp.ns_dhcpX`)
- by editing the configuration, the Unit will add **an additional DHCP server** with the name of the interface, thus not editing the existing one
- Now the UI will show the first one (coming from the migration) and no edit is available
- Workaround is to delete via `uci` the imported configuration.

**Steps to reproduce**

- Migrate from 7 with a DHCP server
- Go to DHCP settings and edit the DHCP server
- Save

**Expected behavior**

- The server gets edited

**Actual behavior**

- A new server gets created, hiding behind the migrated one

**See also**

- [Internal discussion](https://mattermost.nethesis.it/nethesis/pl/ohfpejah3bb5pp9xy6hsquht1a)
 
----

Refs:
- PRs:
  - ~~https://github.com/NethServer/nethsecurity/pull/850~~
  -  https://github.com/NethServer/nethsecurity/pull/856

**Comment by cotosso** [comment]
I tested the updated image and it works as expected, the dhcp server is rightly referenced and editing is effective, i modified leasetime from UI changing it from 1440s to 1240 s.

```
config dhcp 'lan1'
        option interface 'lan1'
        option leasetime '1240m'
        option ignore '0'
        option start '40'
        option limit '115'
        option dhcpv6 'disabled'
        option dhcpv4 'server'
        option force '0'
        list dhcp_option 'option:dns-server,10.16.100.1'

```

**Comment by gsanchietti** [comment]
**Test case 1**
- On a migrate machine, check the issue is not reproducible

**Test case 2**
- Try to configure a new DHCP server
- No error should be raised

**Test case 3**
- Try to configure delete a DHCP server
- No error should be raised

**Comment by francio87** [comment]
Tested using `NethSecurity 8-23.05.5-ns.1.3.0-16-g3de8e46f99a`

**Test Case 1: ok **

```sh
root@ns79:~# uci show dhcp
dhcp.ns_dnsmasq=dnsmasq
dhcp.ns_dnsmasq.domainneeded='1'
dhcp.ns_dnsmasq.boguspriv='1'
dhcp.ns_dnsmasq.filterwin2k='0'
dhcp.ns_dnsmasq.localise_queries='1'
dhcp.ns_dnsmasq.rebind_protection='0'
dhcp.ns_dnsmasq.rebind_localhost='1'
dhcp.ns_dnsmasq.local='/lan/'
dhcp.ns_dnsmasq.domain='kvm.local'
dhcp.ns_dnsmasq.expandhosts='1'
dhcp.ns_dnsmasq.nonegcache='0'
dhcp.ns_dnsmasq.cachesize='4000'
dhcp.ns_dnsmasq.authoritative='1'
dhcp.ns_dnsmasq.readethers='1'
dhcp.ns_dnsmasq.leasefile='/tmp/dhcp.leases'
dhcp.ns_dnsmasq.resolvfile='/tmp/resolv.conf.d/resolv.conf.auto'
dhcp.ns_dnsmasq.nonwildcard='1'
dhcp.ns_dnsmasq.localservice='1'
dhcp.ns_dnsmasq.ednspacket_max='1232'
dhcp.ns_dnsmasq.filter_aaaa='0'
dhcp.ns_dnsmasq.filter_a='0'
dhcp.ns_dnsmasq.enable_tftp='1'
dhcp.ns_dnsmasq.allservers='1'
dhcp.ns_dnsmasq.server='192.168.122.1'
dhcp.odhcpd=odhcpd
dhcp.odhcpd.maindhcp='0'
dhcp.odhcpd.leasefile='/tmp/hosts/odhcpd'
dhcp.odhcpd.leasetrigger='/usr/sbin/odhcpd-update'
dhcp.odhcpd.loglevel='4'
dhcp.ns_dhcp2=dhcp
dhcp.ns_dhcp2.interface='blue_label_net'
dhcp.ns_dhcp2.leasetime='1440m'
dhcp.ns_dhcp2.ignore='0'
dhcp.ns_dhcp2.start='1'
dhcp.ns_dhcp2.limit='253'
dhcp.ns_dhcp2.dhcpv6='disabled'
dhcp.ns_dhcp2.dhcpv4='server'
dhcp.ns_dhcp2.dhcp_option='option:domain-name,bob.com'
dhcp.ns_dhcp1=dhcp
dhcp.ns_dhcp1.interface='FAKE_LAN'
dhcp.ns_dhcp1.leasetime='2h'
dhcp.ns_dhcp1.ignore='0'
dhcp.ns_dhcp1.start='1'
dhcp.ns_dhcp1.limit='253'
dhcp.ns_dhcp1.dhcpv6='disabled'
dhcp.ns_dhcp1.dhcpv4='server'
dhcp.ns_dhcp1.force='0'
dhcp.ns_dhcp1.dhcp_option='option:dns-server,8.8.8.8,8.78.4.4' 'option:domain-name,alice.com'
```
Changed lease time to `2h`

```sh
root@ns79:~# uci changes
dhcp.ns_dhcp1.leasetime='2h'
dhcp.ns_dhcp1.force='0'
-dhcp.ns_dhcp1.dhcp_option
dhcp.ns_dhcp1.dhcp_option+='option:dns-server,8.8.8.8,8.78.4.4'
dhcp.ns_dhcp1.dhcp_option+='option:domain-name,alice.com'
```

The changes are reflected on the UI and there are no duplicate server for the same interface in the cfg

![image](https://github.com/user-attachments/assets/d0a830ba-c26c-442b-ae3e-e60230336f50)


**Test case 2 :** 

Add a new DHCP server, no issue raised

```
root@ns79:~# uci changes
dhcp.lan_test='dhcp'
dhcp.lan_test.dhcpv4='server'
dhcp.lan_test.limit='150'
dhcp.lan_test.start='100'
dhcp.lan_test.leasetime='1h'
dhcp.lan_test.interface='lan_test'
dhcp.lan_test.force='1'
dhcp.lan_test.ignore='0'

```

![image](https://github.com/user-attachments/assets/4888e2d8-13ac-438c-807f-0265ad91adef)
