### ISSUE TITLE
Real IP forwarded with reverse proxy

### ISSUE THREAD

**Issue by MadPatrick** [NethServer/nethsecurity#862]
In the log of the server (for example NS8) with reverse proxy the real IP is not forwarded for Traefik or Nextcloud
Even the internal IP are seen as the Nethsecurity IP (192.168.1.1)
Basically tou can not find in the log the real use (internal user nor external user) all have the Nethsecurity IP

**Proposed solution**

A kind of x-forwarded function

**See also**
https://community.traefik.io/t/how-to-properly-use-x-forwarded-for-in-v2/3834

[Nextcloud configuration](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html)

**Comment by gsanchietti** [comment]
Such info is already forwarded in case of domain-based reverse proxy: it's up to the target destination to use such headers, if the applications wants.
See the [relevant code](https://github.com/NethServer/python3-nethsec/blob/main/src/nethsec/reverse_proxy/__init__.py#L72-L77).

Please open a new discussion on https://communtity.nethserver.org and describe the issue there with all details.
Someone will try to help you.
