### ISSUE TITLE
OpenVPN RW: connection database

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#869]
Display data from connection database: copy the function from NethServer 7.
use only the database saved in RAM.

**Features to Implement:**

- **Add "Last Connection" Field** to the List of Users
- **Connection History for Each User:**
  - **New Action Button** to View Connection History of Every Single User
- **Export Functionality:**
  - **Allow Export of All Data** in CSV Format

![Image](https://github.com/user-attachments/assets/3e86f838-a4d0-4673-b670-7eacc20a6542)

**Comment by stephdl** [comment]
QA

test the new feature relevant to user connexion history


- install openvpn rw 

- test the case without data of user history
- test the case with data of user history 
- download the user history csv

**Comment by mamengoni** [comment]
Tested and verified

![Image](https://github.com/user-attachments/assets/39fe4628-f948-4e7c-bc36-acb64c9b709c)
![Image](https://github.com/user-attachments/assets/f8677126-b76e-415f-8f12-5c9772759f3c)
