### ISSUE TITLE
Objects: cannot use domainset name that starts with a number

### ISSUE THREAD

**Issue by Tbaile** [NethServer/nethsecurity#876]
**Steps to reproduce**

Create a domainset with a starting digit, apply the domainset to what you like

**Expected behavior**

That domainset is created and working when applied

**Actual behavior**

The firewall has issues with the starting digit of the name, not resolving DNS names anymore. Logs:

```
/dev/stdin:15:6-6: Error: syntax error, unexpected number, expecting string or last
    set 1hello {
        ^
```

**Components**

NethSecurity 1.3.0

**See also**

Mattermost Discussion: https://mattermost.nethesis.it/nethesis/pl/cbfse3a7et8d9qfizg8w7wchje

**Comment by andre8244** [comment]
**Testing version**

[23.05.5-ns.1.3.0-23-gbb149f7f124](https://github.com/NethServer/nethsecurity/actions/runs/11614059150/artifacts/2128773112)

**Test case**

Verify the bug is no longer reproducible

**Comment by francio87** [comment]
Confirm fixed ✅ 

![Image](https://github.com/user-attachments/assets/63573a44-431a-4a05-aa3b-088d4154c579)
