### ISSUE TITLE
Domain set objects over 1024 bytes crash Dnsmasq

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/nethsecurity#877]
If the total size of domain names exceeds 1024 bytes Dnsmasq refuses to start (syntax error).

**Steps to reproduce**

- Create a Domain set object with many long names
- Apply config

**Expected behavior**

Dnsmasq running

**Actual behavior**

Dnsmasq stopped, name resolution broken

**See also**

We found and fixed the problem in NethServer 7:
https://github.com/NethServer/nethserver-squid/commit/931f391b0ae5ba3ecd28bb8ddba04157ee37f31b

**Comment by gsanchietti** [comment]
Fix applied for NS7 is not applicable in this scenario, because rules can handle only one set.

I suggest to just add a validator inside the UI.

**Comment by filippocarletti** [comment]
We need to split the single domain set into multiple sets and create a rule for every set.

**Comment by gsanchietti** [comment]
> We need to split the single domain set into multiple sets and create a rule for every set.

Splitting the rules means managing one rule from the UI that translates to multiple rules inside UCI: this is not possible by design.
Nor the object library nor the UI support managing multiple rules from a single entry.

**Comment by andre8244** [comment]
**Testing version**

[23.05.5-ns.1.3.0-23-gbb149f7f124](https://github.com/NethServer/nethsecurity/actions/runs/11614059150/artifacts/2128773112)

**Test case**

Verify the bug is no longer reproducible

**Comment by andre8244** [comment]
After more thorough testing, it appears 1024 is too high as a maximum value, since additional characters will be included in /var/etc/dnsmasq.conf. Gonna submit a PR setting the maximum to 1000 for safety.

**Comment by andre8244** [comment]
Updated testing version: [23.05.5-ns.1.3.0-31-g6a6ff7e](https://github.com/NethServer/nethsecurity/actions/runs/11745118510/artifacts/2163854143)

**Comment by francio87** [comment]
Confirm fixed ✅ 

![Image](https://github.com/user-attachments/assets/c44d3073-7194-4f13-8607-019a676e3e49)
