### ISSUE TITLE
Threat shield detects failed logins but does not block traffic from suspicious IPs

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#878]
**Issue description:**

The `banIP` tool correctly detects failed login attempts and adds suspicious IPs to the blocklist, but traffic from these IPs is not actually blocked. Despite the IP being listed in the blocklist with an active timeout, it continues to be able to send traffic without restriction.

**Evidence of detection:**
```
Oct 30 09:17:36 fw.nethesis.it banIP-1.0.0-9[10451]: suspicious IP '203.0.113.10'
Oct 30 09:17:40 fw.nethesis.it banIP-1.0.0-9[10451]: suspicious IP '203.0.113.10'
Oct 30 09:17:44 fw.nethesis.it banIP-1.0.0-9[10451]: suspicious IP '203.0.113.10'
Oct 30 09:17:44 fw.nethesis.it banIP-1.0.0-9[10451]: add IP '203.0.113.10' (expiry: 30m) to blocklistv4 set
```

**Blocklist set content:**
```
~# nft list set inet banIP blocklistv4
table inet banIP {
	set blocklistv4 {
		type ipv4_addr
		policy memory
		flags interval,timeout
		auto-merge
		elements = { 203.0.113.10 timeout 30m expires 28m47s230ms }
	}
}
```

**Current behavior:**
- Future traffic from IP `203.0.113.10` should be blocked, as it is present in the `blocklistv4` set with a timeout, but traffic continues to pass without restrictions.

**Expected behavior:**
- Traffic from any IPs listed in `blocklistv4` should be effectively blocked by `banIP`.

**Components:**
NethSecurity Image: 8-23.05.4-ns.1.3.0

Reference:
- https://community.nethserver.org/t/threat-shield-seems-not-working/24835

---

Thanks to **Igonet** and **izuky**

**Comment by Tbaile** [comment]
Dived down the rabbit hole, and found out that the "bug" is triggered by a `conntrack` record stale that is alive while banIP sets the banned ip in the `wan-input` chain.

To prove this, do as follows:

1. Make your ip banned from banIP (careful, this must come from outside the WAN network)
2. Access the machine correctly
3. Go to conntrack management and flush the table
4. Connection is banned correctly (try SSHing in the machine)
