### ISSUE TITLE
UI Threat shield ban

### ISSUE THREAD

**Issue by andre8244** [NethServer/nethsecurity#881]
In Threat shield Settings, change element order in the "Prevent brute force attacks" subsection.
Enable "Block brute force attack" will enable also, in order:

1. Ban after x failed access
2. Ban time
3. Pattern to search for attacks

![Image](https://github.com/user-attachments/assets/145a1f5d-39ac-4754-85a0-1c7a0c482b9d)

**Comment by andre8244** [comment]
**Testing version**

[23.05.5-ns.1.3.0-23-gbb149f7f124](https://github.com/NethServer/nethsecurity/actions/runs/11614059150/artifacts/2128773112)

**Test case**

Verify the order of appearance of the fields

**Comment by cotosso** [comment]
Order of appearance has been fixed.
