### ISSUE TITLE
Port forward:  ipset entries not removed after port forward deletion

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#895]
**Steps to reproduce**
1. Create a regular port forward
2. Create a port forward with restricted access (using an object or specific IP addresses, only hostsets or IPs).
3. Remove both the port forwards

**Expected behavior**
- The related IP sets should be removed from `/etc/config/firewall`.

**Actual behavior**
- The IP sets remain in `/etc/config/firewall` even though there are no rules using them.

**Components**
NethSecurity version: 8-23.05.5-ns.1.3.0

**Comment by Tbaile** [comment]
Image: [23.05.5-ns.1.3.0-32-g375f3b5](https://github.com/NethServer/nethsecurity/actions/runs/11799913401/artifacts/2176892255)

Using the image above, repeat the reproduction steps and ensure deletion has 2 entries deleted (both redirect and ipset) goes smoothly.

**Comment by francio87** [comment]
Confirm fixed ✅ 

Created two port forwarding rules: the first has restricted access using a host set object.

```sh
        chain dstnat_wan {
                tcp dport 6000 ip saddr @ns_cd1c7c25_ipset counter packets 0 bytes 0 dnat ip to 10.20.50.3:6000 comment "!fw4: pftest"
                udp dport 6000 ip saddr @ns_cd1c7c25_ipset counter packets 0 bytes 0 dnat ip to 10.20.50.3:6000 comment "!fw4: pftest"
                meta nfproto ipv4 tcp dport 7000 counter packets 0 bytes 0 dnat ip to 10.20.50.3:7000 comment "!fw4: pftest2"
                meta nfproto ipv4 udp dport 7000 counter packets 0 bytes 0 dnat ip to 10.20.50.3:7000 comment "!fw4: pftest2"
        }
```

```sh
root@NethSec:~# nft list set inet fw4 ns_cd1c7c25_ipset
table inet fw4 {
        set ns_cd1c7c25_ipset {
                type ipv4_addr
                flags interval
                auto-merge
                elements = { 8.8.4.4, 8.8.8.8,
                             9.9.9.9 }
        }
}
```

```sh
root@NethSec:~# tail -10 /etc/config/firewall

config ipset 'ns_cd1c7c25_ipset'
        option name 'ns_cd1c7c25_ipset'
        option match 'src_net'
        option enabled '1'
        option ns_link 'firewall/ns_cd1c7c25'
        list entry '8.8.4.4/32'
        list entry '9.9.9.9/32'
        list entry '8.8.8.8'
```

Removed both port forward :

```sh
root@NethSec:~# uci changes
-firewall.ns_cd1c7c25_ipset
-firewall.ns_cd1c7c25
-firewall.ns_27c3dadc
```

ipset is removed from the config :

```sh
root@NethSec:~# grep ns_cd1c7c25_ipset /etc/config/firewall
root@NethSec:~#
```
