### ISSUE TITLE
Firewall rules: mockup for invalid rules

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#902]
Mockup for parent issue #899

**Comment by AmaLuci** [comment]
![Image](https://github.com/user-attachments/assets/fe22babc-035f-42a4-ba69-2866fba591bd)

**Comment by AmaLuci** [comment]
In the mockup, inactive rules are marked with an orange "badge" containing a warning icon. This update also includes adjusting the display of the "disabled" status to ensure consistency between statuses (both using badges).

The badge should include a descriptive tooltip.

Rule cards should be reviewed (padding, margins, etc.) to align with the mockup's layout.

Adding search filters to the Rules page would also be ideal.
