### ISSUE TITLE
Port forward: mockup for invalid port forwards

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#903]
Create mockup for parent task: #898

**Comment by AmaLuci** [comment]
![Image](https://github.com/user-attachments/assets/a8d78f32-ec59-4634-856a-b6f062d7b1bc)
![Image](https://github.com/user-attachments/assets/6e52db04-baba-4e2c-8197-d06f83864626)

**Comment by AmaLuci** [comment]
![Image](https://github.com/user-attachments/assets/5daa41b7-b7f7-42dc-97f3-0b602af0d3f1)
![Image](https://github.com/user-attachments/assets/10a51e84-5607-4fee-8431-2f9b91389536)
