### ISSUE TITLE
Realtime monitoring: latency and drop rate charts

### ISSUE THREAD

**Issue by andre8244** [NethServer/nethsecurity#904]
API and UI is missing for these Connectivity charts:
- Latency graphs to public hosts, same time window as the above chart
- Drop rate graphs to public hosts, same time windows as the above chart

See description of issue: https://github.com/NethServer/nethsecurity/issues/756

**Comment by andre8244** [comment]
### Testing image
[23.05.5-ns.1.3.0-46-g66c952f](https://github.com/NethServer/nethsecurity/actions/runs/11908799716/artifacts/2205967904)

### Test Case 1: Ping Latency Monitor Not Configured

1. Navigate to **Monitoring > Ping Latency Monitor**.  
2. Confirm that no **Hosts to Monitor** are configured.  
3. Go to **Monitoring > Real-Time Monitor > Connectivity**.  
4. Verify that a card displaying the empty state message, *"No hosts configured for monitoring"*, is shown.  

---

### Test Case 2: Ping Latency Monitor Configured

1. Navigate to **Monitoring > Ping Latency Monitor**.  
2. Confirm that at least one **Host to Monitor** is configured.  
3. Go to **Monitoring > Real-Time Monitor > Connectivity**.  
4. Verify that the following charts are displayed for each configured host:  
   - Latency to {pingHost}
   - Packet Delivery Rate to {pingHost}

**Comment by andre8244** [comment]
Updated testing image: [23.05.5-ns.1.3.0-49-g597f6078](https://github.com/NethServer/nethsecurity/actions/runs/11937235707/artifacts/2214097449)

**Comment by gsanchietti** [comment]
Both test cases verified: packet loss simulated using a nft rules.
