### ISSUE TITLE
Mockup for Threat Shield DNS UI

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#907]
Create a mockup for the parent issue: #906 

The module can be similar to Threat Shield IP, it should be composed by the following views.
FlashStart and Threat Shield DNS UI are mutually exclusive: the UI should handle di case

**Settings**

This page allows to configure the filter basic settings.

Expose:
- a button to enable and disable the filter
- a select option to choose one ore more zone where the filter will by applied
- an editable list of DNS redirected ports: the default list is composed by 2 ports, integer numbers. The list is populated
  as soon as the filter is enabled, but we could display good defaults. The list can't be empty.

**Blocklist sources**

This page shows the available list sources, each source can be enabled or disabled.

Expose:
- a table of all available lists
- make sure to display the confidence and the type (community or enterprise)

**Local blocklist**

This page show a local blocklist of domains.
The user should be able to add or remove custom domains.

**Bypass**

This page should allow the user to create a bypass of the filter for hosts inside the local zones (eg. LAN).

The bypass can be done on IP basis, but the mockup could explore also the use of firewall objects.

**Comment by AmaLuci** [comment]
Mockups ready in [Figma](https://www.figma.com/design/FhVUA3F59rOsQPh2bDlZ7V/NethSecurity-shared-file?node-id=2293-31024&node-type=frame&t=6kEnnUJuQxOrEMnq-0)
