### ISSUE TITLE
Mockup for IPS UI

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#910]
Create a mockup for the Snort IPS, see parent issue: #976

The mockup should implement the following views.

**Settings page**

The page should allow the following configuration:
- enable or disable the service
- select one rule policy between: "connectivity", "balanced" and "security"
- add or remove an optional oinkcode (text string), a key that is used to download rules with a subscription from Snort site
- a list of disabled rules
- advanced: enable or disable the inclusion of VPN networks inside the HOME_NET variable

The UI should also show in this page, or somewhere else, the following information:
- number of downloaded rules
- time of the last rules download
- evaluate if a button to force download can be useful

**Bypass IDS**

This page should allow the user to add one ore more local IPv4/IPv6 addresses that are not filtered by the IPS.
Evaluate also a mockup that uses firewall objects instead of simple IP addresses.

Each bypass has 3 options:

- direction: source or destination
- type: IPv4/IPv6
- address: the actual IP address

**Alert list**

The page should:
- display all alerts from the current day
- by clicking on an alert, the user should be able to disable or suppress the selected rule

Disable a rule: the rule is excluded from the configuration.
Actions:
- add the rule to the disabled list rules, such list should be visible and editable somewhere
- a disabled rule could has the following fields:
  - the rule SID (integer)
  - an optional description

Suppress a rule: the rule is ignored for certain IP address.
Actions:
- add the rule to the suppression rule list
- a suppressed rule has the following fields:
  - the GID so suppress, it's always 1, probably we can omit it from the UI
  - the rule SID
  - the direction of the suppression: it can be "source" or "destination"
  - the IP or CIDR on which the suppression apply
  - an optional description

**Monitoring**

The mockup should also take care of adding new charts to:

- local monitoring page
- monitoring page on controller

**Comment by AmaLuci** [comment]
Mockups in [Figma](https://www.figma.com/design/FhVUA3F59rOsQPh2bDlZ7V/NethSecurity-shared-file?node-id=2352-50095&node-type=frame&t=ZZvKjRKb0CDSP8lD-0)

**Comment by gsanchietti** [comment]
Approved.
