### ISSUE TITLE
Migration: PPPoE alias import fails with invalid argument error

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#913]
**Steps to reproduce**
- On NethServer 7, create aliases on the PPPoE interface.
- Export the archive
- Attempt to import the export.tar.gz archive into NethSecurity 8.

**Expected behavior**
- The archive should be imported successfully, with PPPoE aliases correctly set to the `wan` zone.

**Actual behavior**
- Import process fails with an "Invalid argument" error when setting the zone for PPPoE aliases.
- Error message:
  ```
  Creating zone lan
  Traceback (most recent call last):
    File "/usr/share/ns-migration/20network", line 311, in <module>
      u.set("firewall", zname, "network", [utils.sanitize(n) for n in network])
    File "/usr/lib/python3.11/site-packages/euci/__init__.py", line 133, in set
  uci.UciException: Invalid argument
  ```

Example excerpt from export.json with redacted IPs and MAC addresses:
  ```json
  {
    "aliases": [
      {
        "proto": "static",
        "zone": "pppoe",
        "netmask": "255.255.255.248",
        "hwaddr": "00:xx:xx:xx:xx:xx",
        "ipaddr": "xx.xx.xx.xx"
      },
      {
        "proto": "static",
        "zone": "pppoe",
        "netmask": "255.255.255.248",
        "hwaddr": "00:xx:xx:xx:xx:xx",
        "ipaddr": "xx.xx.xx.xx"
      },
      {
        "proto": "static",
        "zone": "wan",
        "gateway": "",
        "netmask": "255.255.255.248",
        "hwaddr": "00:xx:xx:xx:xx:xx",
        "ipaddr": "xx.xx.xx.xx"
      }
    ]
  }
  ```

**Components**
NethSecurity version: 8-23.05.5-ns.1.3.0

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-firewall-migration-1.0.2-1.5.g1fcf4e1.ns7.noarch.rpm

**Test case**
Check the issue is not reproducible

**Comment by francio87** [comment]
Confirm Fixed
