### ISSUE TITLE
FlashStart: disable if no subscription

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#926]
If the machine has no Subscription, the FlahStart configuration should be disabled.
The UI should display an empty state with an explanation of the error and a link to the Subscription pagae.

**Comment by stephdl** [comment]
QA

- install nethsecurity testing
- go to the security > flashstart filter
- a new empty state message prevent you the subscription is not enabled
- click on the button go to subscription
- set you subscription token
- go back to security > flashstart filter
- you can configure flash start

**Comment by gsanchietti** [comment]
Test case verified: FlashStart is configurable only if the subscription has been enabled.

**Comment by gsanchietti** [comment]
Released on 23.05.5-ns.1.4.0
