### ISSUE TITLE
Hotspot: verify community subscription

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#930]
Implement changes to the client to authenticate the use of the hotspot service using the following command:
```
curl -s 'https://UUID:SECRET@my.nethserver.com/api/auth/service/hotspot'
```

This is not just a cosmetic improvement, it is necessary to verify that the firewall has indeed purchased the hotspot product and thus is allowed to add units.

**Task:**

1. Implement the authentication check using the provided curl command.
2. Ensure the authentication verifies that the firewall is entitled to use the hotspot service.

**Notes:**

- Simply being able to log in may be acceptable as a compromise but does not constitute true validation.
- A user might destroy and recreate a machine without hotspot, yet still retain and use credentials obtained from a previous valid login.

**Comment by stephdl** [comment]
won't fix
