### ISSUE TITLE
Monitoring: error when OpenVPN RoadWarrior has an incomplete configuration

### ISSUE THREAD

**Issue by Tbaile** [NethServer/nethsecurity#943]
OpenVPN RoadWarrior creates a "dummy" server even if you dismiss it's initial setup.

**Steps to reproduce**

- Go to `OpenVPN Road Warrior`
- Click the provided `Create Server` button 
- Dismiss the form of the sidebar with either `Cancel` or by pressing `ESC`
- Navigate under `Monitoring` -> `Real time monitor` -> `VPN`

**Expected behavior**

No OpenVPN server should appear.

**Actual behavior**

Issues arise due to the backend creating a "placeholder" server but all APIs give errors due to missing data:
- ns.ovpnrw list-users
- ns.report ovpnrw-bytes-by-hour
- ns.report ovpnrw-clients-by-day
- ns.report ovpnrw-count-clients-by-hour

**Components**

Image version: 8-23.05.5-ns.1.3.0

**See also**

Ref: 
- Community Discussion: https://community.nethserver.org/t/bug-openvpn-road-worrier-is-creating-hidden-config/24963

----

Thanks to mz05er

**Comment by gsanchietti** [comment]
Testing image: 23.05.5-ns.1.3.0-93-g225c40bf


**Test case**

Check the issue is not reproducible

**Comment by gsanchietti** [comment]
Released on 23.05.5-ns.1.4.0
