### ISSUE TITLE
Fork mwan3 to add rules for router initiated traffic

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/nethsecurity#963]
The maintainer of mwan3 has been unable to test and merge the PR to handle router-initiated traffic
We need to fork mwan3 to have the feature.

See https://github.com/openwrt/packages/pull/25121 for the details.

**Comment by gsanchietti** [comment]
Test case verified on WANs without sNAT.
On a WAN with sNAT configured, the natted IP is retuned.

**Comment by gsanchietti** [comment]
Released on 23.05.5-ns.1.4.0
