### ISSUE TITLE
Mockup for informatics UI

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/nethsecurity#982]
Create mockup for parent issue #981

**Comment by AmaLuci** [comment]
Mockups in [Figma](https://www.figma.com/design/FhVUA3F59rOsQPh2bDlZ7V/NethSecurity-shared-file?node-id=2436-122604&t=okEQygLl5OCDXAPP-0)

**Comment by gsanchietti** [comment]
Looks good to me.

**Comment by andre8244** [comment]
LGTM too ✅

**Comment by gsanchietti** [comment]
Ready to be implemented.
